// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: starchart.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RegistryService_PutChart_FullMethodName         = "/starchart.RegistryService/PutChart"
	RegistryService_GetChartMetadata_FullMethodName = "/starchart.RegistryService/GetChartMetadata"
	RegistryService_GetChartsLabels_FullMethodName  = "/starchart.RegistryService/GetChartsLabels"
	RegistryService_DeleteChart_FullMethodName      = "/starchart.RegistryService/DeleteChart"
)

// RegistryServiceClient is the client API for RegistryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RegistryServiceClient interface {
	PutChart(ctx context.Context, in *StarChart, opts ...grpc.CallOption) (*PutChartResp, error)
	GetChartMetadata(ctx context.Context, in *GetChartFromMetadataReq, opts ...grpc.CallOption) (*GetChartFromMetadataResp, error)
	GetChartsLabels(ctx context.Context, in *GetChartsLabelsReq, opts ...grpc.CallOption) (*GetChartsLabelsResp, error)
	DeleteChart(ctx context.Context, in *DeleteChartReq, opts ...grpc.CallOption) (*EmptyMessage, error)
}

type registryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRegistryServiceClient(cc grpc.ClientConnInterface) RegistryServiceClient {
	return &registryServiceClient{cc}
}

func (c *registryServiceClient) PutChart(ctx context.Context, in *StarChart, opts ...grpc.CallOption) (*PutChartResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutChartResp)
	err := c.cc.Invoke(ctx, RegistryService_PutChart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryServiceClient) GetChartMetadata(ctx context.Context, in *GetChartFromMetadataReq, opts ...grpc.CallOption) (*GetChartFromMetadataResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChartFromMetadataResp)
	err := c.cc.Invoke(ctx, RegistryService_GetChartMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryServiceClient) GetChartsLabels(ctx context.Context, in *GetChartsLabelsReq, opts ...grpc.CallOption) (*GetChartsLabelsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChartsLabelsResp)
	err := c.cc.Invoke(ctx, RegistryService_GetChartsLabels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryServiceClient) DeleteChart(ctx context.Context, in *DeleteChartReq, opts ...grpc.CallOption) (*EmptyMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyMessage)
	err := c.cc.Invoke(ctx, RegistryService_DeleteChart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistryServiceServer is the server API for RegistryService service.
// All implementations must embed UnimplementedRegistryServiceServer
// for forward compatibility.
type RegistryServiceServer interface {
	PutChart(context.Context, *StarChart) (*PutChartResp, error)
	GetChartMetadata(context.Context, *GetChartFromMetadataReq) (*GetChartFromMetadataResp, error)
	GetChartsLabels(context.Context, *GetChartsLabelsReq) (*GetChartsLabelsResp, error)
	DeleteChart(context.Context, *DeleteChartReq) (*EmptyMessage, error)
	mustEmbedUnimplementedRegistryServiceServer()
}

// UnimplementedRegistryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRegistryServiceServer struct{}

func (UnimplementedRegistryServiceServer) PutChart(context.Context, *StarChart) (*PutChartResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutChart not implemented")
}
func (UnimplementedRegistryServiceServer) GetChartMetadata(context.Context, *GetChartFromMetadataReq) (*GetChartFromMetadataResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChartMetadata not implemented")
}
func (UnimplementedRegistryServiceServer) GetChartsLabels(context.Context, *GetChartsLabelsReq) (*GetChartsLabelsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChartsLabels not implemented")
}
func (UnimplementedRegistryServiceServer) DeleteChart(context.Context, *DeleteChartReq) (*EmptyMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteChart not implemented")
}
func (UnimplementedRegistryServiceServer) mustEmbedUnimplementedRegistryServiceServer() {}
func (UnimplementedRegistryServiceServer) testEmbeddedByValue()                         {}

// UnsafeRegistryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegistryServiceServer will
// result in compilation errors.
type UnsafeRegistryServiceServer interface {
	mustEmbedUnimplementedRegistryServiceServer()
}

func RegisterRegistryServiceServer(s grpc.ServiceRegistrar, srv RegistryServiceServer) {
	// If the following call pancis, it indicates UnimplementedRegistryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RegistryService_ServiceDesc, srv)
}

func _RegistryService_PutChart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StarChart)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).PutChart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryService_PutChart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).PutChart(ctx, req.(*StarChart))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryService_GetChartMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChartFromMetadataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).GetChartMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryService_GetChartMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).GetChartMetadata(ctx, req.(*GetChartFromMetadataReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryService_GetChartsLabels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChartsLabelsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).GetChartsLabels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryService_GetChartsLabels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).GetChartsLabels(ctx, req.(*GetChartsLabelsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryService_DeleteChart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteChartReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).DeleteChart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryService_DeleteChart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).DeleteChart(ctx, req.(*DeleteChartReq))
	}
	return interceptor(ctx, in, info, handler)
}

// RegistryService_ServiceDesc is the grpc.ServiceDesc for RegistryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RegistryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "starchart.RegistryService",
	HandlerType: (*RegistryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutChart",
			Handler:    _RegistryService_PutChart_Handler,
		},
		{
			MethodName: "GetChartMetadata",
			Handler:    _RegistryService_GetChartMetadata_Handler,
		},
		{
			MethodName: "GetChartsLabels",
			Handler:    _RegistryService_GetChartsLabels_Handler,
		},
		{
			MethodName: "DeleteChart",
			Handler:    _RegistryService_DeleteChart_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "starchart.proto",
}
