// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: starmap_model.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyMessage) Reset() {
	*x = EmptyMessage{}
	mi := &file_starmap_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyMessage) ProtoMessage() {}

func (x *EmptyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyMessage.ProtoReflect.Descriptor instead.
func (*EmptyMessage) Descriptor() ([]byte, []int) {
	return file_starmap_model_proto_rawDescGZIP(), []int{0}
}

type EntrypointLinks struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// NOTE: some gRPC clients (Postman) don't serialize this oneof correctly,
	// so send entrypoints through the lunar-gateway or curl instead.
	//
	// Types that are valid to be assigned to Link:
	//
	//	*EntrypointLinks_Command
	//	*EntrypointLinks_Entrypoint
	//	*EntrypointLinks_Run
	Link          isEntrypointLinks_Link `protobuf_oneof:"link"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntrypointLinks) Reset() {
	*x = EntrypointLinks{}
	mi := &file_starmap_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntrypointLinks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntrypointLinks) ProtoMessage() {}

func (x *EntrypointLinks) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntrypointLinks.ProtoReflect.Descriptor instead.
func (*EntrypointLinks) Descriptor() ([]byte, []int) {
	return file_starmap_model_proto_rawDescGZIP(), []int{1}
}

func (x *EntrypointLinks) GetLink() isEntrypointLinks_Link {
	if x != nil {
		return x.Link
	}
	return nil
}

func (x *EntrypointLinks) GetCommand() *CommandLink {
	if x != nil {
		if x, ok := x.Link.(*EntrypointLinks_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *EntrypointLinks) GetEntrypoint() *EntrypointLink {
	if x != nil {
		if x, ok := x.Link.(*EntrypointLinks_Entrypoint); ok {
			return x.Entrypoint
		}
	}
	return nil
}

func (x *EntrypointLinks) GetRun() *RunLink {
	if x != nil {
		if x, ok := x.Link.(*EntrypointLinks_Run); ok {
			return x.Run
		}
	}
	return nil
}

type isEntrypointLinks_Link interface {
	isEntrypointLinks_Link()
}

type EntrypointLinks_Command struct {
	Command *CommandLink `protobuf:"bytes,1,opt,name=command,proto3,oneof"`
}

type EntrypointLinks_Entrypoint struct {
	Entrypoint *EntrypointLink `protobuf:"bytes,2,opt,name=entrypoint,proto3,oneof"`
}

type EntrypointLinks_Run struct {
	Run *RunLink `protobuf:"bytes,3,opt,name=run,proto3,oneof"`
}

func (*EntrypointLinks_Command) isEntrypointLinks_Link() {}

func (*EntrypointLinks_Entrypoint) isEntrypointLinks_Link() {}

func (*EntrypointLinks_Run) isEntrypointLinks_Link() {}

type Entrypoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Control       *Control               `protobuf:"bytes,2,opt,name=control,proto3" json:"control,omitempty"`
	Features      *Features              `protobuf:"bytes,3,opt,name=features,proto3" json:"features,omitempty"`
	Links         *EntrypointLinks       `protobuf:"bytes,4,opt,name=links,proto3" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entrypoint) Reset() {
	*x = Entrypoint{}
	mi := &file_starmap_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entrypoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entrypoint) ProtoMessage() {}

func (x *Entrypoint) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entrypoint.ProtoReflect.Descriptor instead.
func (*Entrypoint) Descriptor() ([]byte, []int) {
	return file_starmap_model_proto_rawDescGZIP(), []int{2}
}

func (x *Entrypoint) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Entrypoint) GetControl() *Control {
	if x != nil {
		return x.Control
	}
	return nil
}

func (x *Entrypoint) GetFeatures() *Features {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *Entrypoint) GetLinks() *EntrypointLinks {
	if x != nil {
		return x.Links
	}
	return nil
}

type CommandLink struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Metadata      *CommandLink_CommandLinkMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Destination   string                           `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandLink) Reset() {
	*x = CommandLink{}
	mi := &file_starmap_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandLink) ProtoMessage() {}

func (x *CommandLink) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandLink.ProtoReflect.Descriptor instead.
func (*CommandLink) Descriptor() ([]byte, []int) {
	return file_starmap_model_proto_rawDescGZIP(), []int{3}
}

func (x *CommandLink) GetMetadata() *CommandLink_CommandLinkMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CommandLink) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

type EntrypointLink struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	Metadata      *EntrypointLink_EntrypointLinkMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Destination   string                                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntrypointLink) Reset() {
	*x = EntrypointLink{}
	mi := &file_starmap_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntrypointLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntrypointLink) ProtoMessage() {}

func (x *EntrypointLink) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntrypointLink.ProtoReflect.Descriptor instead.
func (*EntrypointLink) Descriptor() ([]byte, []int) {
	return file_starmap_model_proto_rawDescGZIP(), []int{4}
}

func (x *EntrypointLink) GetMetadata() *EntrypointLink_EntrypointLinkMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *EntrypointLink) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

type RunLink struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Metadata      *RunLink_RunLinkMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Destination   string                   `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunLink) Reset() {
	*x = RunLink{}
	mi := &file_starmap_model_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunLink) ProtoMessage() {}

func (x *RunLink) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_model_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunLink.ProtoReflect.Descriptor instead.
func (*RunLink) Descriptor() ([]byte, []int) {
	return file_starmap_model_proto_rawDescGZIP(), []int{5}
}

func (x *RunLink) GetMetadata() *RunLink_RunLinkMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RunLink) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

type DataSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	ResourceName  string                 `protobuf:"bytes,5,opt,name=resourceName,proto3" json:"resourceName,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tags          map[string]string      `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataSource) Reset() {
	*x = DataSource{}
	mi := &file_starmap_model_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataSource) ProtoMessage() {}

func (x *DataSource) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_model_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataSource.ProtoReflect.Descriptor instead.
func (*DataSource) Descriptor() ([]byte, []int) {
	return file_starmap_model_proto_rawDescGZIP(), []int{6}
}

func (x *DataSource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DataSource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DataSource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DataSource) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DataSource) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *DataSource) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DataSource) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *DataSource) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Build         *Build                 `protobuf:"bytes,4,opt,name=build,proto3" json:"build,omitempty"`
	Prefix        string                 `protobuf:"bytes,5,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Topic         string                 `protobuf:"bytes,6,opt,name=topic,proto3" json:"topic,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tags          map[string]string      `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_starmap_model_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_model_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_starmap_model_proto_rawDescGZIP(), []int{7}
}

func (x *Metadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Metadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metadata) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Metadata) GetBuild() *Build {
	if x != nil {
		return x.Build
	}
	return nil
}

func (x *Metadata) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *Metadata) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Metadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Metadata) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Metadata) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type Build struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pull          string                 `protobuf:"bytes,1,opt,name=pull,proto3" json:"pull,omitempty"`
	Workdir       string                 `protobuf:"bytes,2,opt,name=workdir,proto3" json:"workdir,omitempty"`
	Command       string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Build) Reset() {
	*x = Build{}
	mi := &file_starmap_model_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Build) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Build) ProtoMessage() {}

func (x *Build) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_model_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Build.ProtoReflect.Descriptor instead.
func (*Build) Descriptor() ([]byte, []int) {
	return file_starmap_model_proto_rawDescGZIP(), []int{8}
}

func (x *Build) GetPull() string {
	if x != nil {
		return x.Pull
	}
	return ""
}

func (x *Build) GetWorkdir() string {
	if x != nil {
		return x.Workdir
	}
	return ""
}

func (x *Build) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type Control struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	DisableVirtualization bool                   `protobuf:"varint,1,opt,name=disableVirtualization,proto3" json:"disableVirtualization,omitempty"`
	RunDetached           bool                   `protobuf:"varint,2,opt,name=runDetached,proto3" json:"runDetached,omitempty"`
	RemoveOnStop          bool                   `protobuf:"varint,3,opt,name=removeOnStop,proto3" json:"removeOnStop,omitempty"`
	Memory                string                 `protobuf:"bytes,4,opt,name=memory,proto3" json:"memory,omitempty"`
	KernelArgs            string                 `protobuf:"bytes,5,opt,name=kernelArgs,proto3" json:"kernelArgs,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Control) Reset() {
	*x = Control{}
	mi := &file_starmap_model_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Control) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Control) ProtoMessage() {}

func (x *Control) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_model_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Control.ProtoReflect.Descriptor instead.
func (*Control) Descriptor() ([]byte, []int) {
	return file_starmap_model_proto_rawDescGZIP(), []int{9}
}

func (x *Control) GetDisableVirtualization() bool {
	if x != nil {
		return x.DisableVirtualization
	}
	return false
}

func (x *Control) GetRunDetached() bool {
	if x != nil {
		return x.RunDetached
	}
	return false
}

func (x *Control) GetRemoveOnStop() bool {
	if x != nil {
		return x.RemoveOnStop
	}
	return false
}

func (x *Control) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

func (x *Control) GetKernelArgs() string {
	if x != nil {
		return x.KernelArgs
	}
	return ""
}

type Features struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Networks      []string               `protobuf:"bytes,1,rep,name=networks,proto3" json:"networks,omitempty"`
	Ports         []string               `protobuf:"bytes,2,rep,name=ports,proto3" json:"ports,omitempty"`
	Volumes       []string               `protobuf:"bytes,3,rep,name=volumes,proto3" json:"volumes,omitempty"`
	Targets       []string               `protobuf:"bytes,4,rep,name=targets,proto3" json:"targets,omitempty"`
	EnvVars       []string               `protobuf:"bytes,5,rep,name=envVars,proto3" json:"envVars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Features) Reset() {
	*x = Features{}
	mi := &file_starmap_model_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Features) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Features) ProtoMessage() {}

func (x *Features) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_model_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Features.ProtoReflect.Descriptor instead.
func (*Features) Descriptor() ([]byte, []int) {
	return file_starmap_model_proto_rawDescGZIP(), []int{10}
}

func (x *Features) GetNetworks() []string {
	if x != nil {
		return x.Networks
	}
	return nil
}

func (x *Features) GetPorts() []string {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *Features) GetVolumes() []string {
	if x != nil {
		return x.Volumes
	}
	return nil
}

func (x *Features) GetTargets() []string {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *Features) GetEnvVars() []string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

type Links struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SoftLinks     []string               `protobuf:"bytes,1,rep,name=softLinks,proto3" json:"softLinks,omitempty"`
	HardLinks     []string               `protobuf:"bytes,2,rep,name=hardLinks,proto3" json:"hardLinks,omitempty"`
	EventLinks    []string               `protobuf:"bytes,3,rep,name=eventLinks,proto3" json:"eventLinks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Links) Reset() {
	*x = Links{}
	mi := &file_starmap_model_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Links) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Links) ProtoMessage() {}

func (x *Links) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_model_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Links.ProtoReflect.Descriptor instead.
func (*Links) Descriptor() ([]byte, []int) {
	return file_starmap_model_proto_rawDescGZIP(), []int{11}
}

func (x *Links) GetSoftLinks() []string {
	if x != nil {
		return x.SoftLinks
	}
	return nil
}

func (x *Links) GetHardLinks() []string {
	if x != nil {
		return x.HardLinks
	}
	return nil
}

func (x *Links) GetEventLinks() []string {
	if x != nil {
		return x.EventLinks
	}
	return nil
}

type StoredProcedure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Control       *Control               `protobuf:"bytes,2,opt,name=control,proto3" json:"control,omitempty"`
	Features      *Features              `protobuf:"bytes,3,opt,name=features,proto3" json:"features,omitempty"`
	Links         *Links                 `protobuf:"bytes,4,opt,name=links,proto3" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoredProcedure) Reset() {
	*x = StoredProcedure{}
	mi := &file_starmap_model_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoredProcedure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoredProcedure) ProtoMessage() {}

func (x *StoredProcedure) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_model_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoredProcedure.ProtoReflect.Descriptor instead.
func (*StoredProcedure) Descriptor() ([]byte, []int) {
	return file_starmap_model_proto_rawDescGZIP(), []int{12}
}

func (x *StoredProcedure) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *StoredProcedure) GetControl() *Control {
	if x != nil {
		return x.Control
	}
	return nil
}

func (x *StoredProcedure) GetFeatures() *Features {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *StoredProcedure) GetLinks() *Links {
	if x != nil {
		return x.Links
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Control       *Control               `protobuf:"bytes,2,opt,name=control,proto3" json:"control,omitempty"`
	Features      *Features              `protobuf:"bytes,3,opt,name=features,proto3" json:"features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_starmap_model_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_model_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_starmap_model_proto_rawDescGZIP(), []int{13}
}

func (x *Event) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Event) GetControl() *Control {
	if x != nil {
		return x.Control
	}
	return nil
}

func (x *Event) GetFeatures() *Features {
	if x != nil {
		return x.Features
	}
	return nil
}

type EventTrigger struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Control       *Control               `protobuf:"bytes,2,opt,name=control,proto3" json:"control,omitempty"`
	Features      *Features              `protobuf:"bytes,3,opt,name=features,proto3" json:"features,omitempty"`
	Links         *Links                 `protobuf:"bytes,4,opt,name=links,proto3" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventTrigger) Reset() {
	*x = EventTrigger{}
	mi := &file_starmap_model_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventTrigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventTrigger) ProtoMessage() {}

func (x *EventTrigger) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_model_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventTrigger.ProtoReflect.Descriptor instead.
func (*EventTrigger) Descriptor() ([]byte, []int) {
	return file_starmap_model_proto_rawDescGZIP(), []int{14}
}

func (x *EventTrigger) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *EventTrigger) GetControl() *Control {
	if x != nil {
		return x.Control
	}
	return nil
}

func (x *EventTrigger) GetFeatures() *Features {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *EventTrigger) GetLinks() *Links {
	if x != nil {
		return x.Links
	}
	return nil
}

type Chart struct {
	state            protoimpl.MessageState      `protogen:"open.v1"`
	DataSources      map[string]*DataSource      `protobuf:"bytes,1,rep,name=dataSources,proto3" json:"dataSources,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StoredProcedures map[string]*StoredProcedure `protobuf:"bytes,2,rep,name=storedProcedures,proto3" json:"storedProcedures,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	EventTriggers    map[string]*EventTrigger    `protobuf:"bytes,3,rep,name=eventTriggers,proto3" json:"eventTriggers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Events           map[string]*Event           `protobuf:"bytes,4,rep,name=events,proto3" json:"events,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Entrypoints      map[string]*Entrypoint      `protobuf:"bytes,5,rep,name=entrypoints,proto3" json:"entrypoints,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Chart) Reset() {
	*x = Chart{}
	mi := &file_starmap_model_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chart) ProtoMessage() {}

func (x *Chart) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_model_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chart.ProtoReflect.Descriptor instead.
func (*Chart) Descriptor() ([]byte, []int) {
	return file_starmap_model_proto_rawDescGZIP(), []int{15}
}

func (x *Chart) GetDataSources() map[string]*DataSource {
	if x != nil {
		return x.DataSources
	}
	return nil
}

func (x *Chart) GetStoredProcedures() map[string]*StoredProcedure {
	if x != nil {
		return x.StoredProcedures
	}
	return nil
}

func (x *Chart) GetEventTriggers() map[string]*EventTrigger {
	if x != nil {
		return x.EventTriggers
	}
	return nil
}

func (x *Chart) GetEvents() map[string]*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *Chart) GetEntrypoints() map[string]*Entrypoint {
	if x != nil {
		return x.Entrypoints
	}
	return nil
}

type MetadataChart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Maintainer    string                 `protobuf:"bytes,4,opt,name=maintainer,proto3" json:"maintainer,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Visibility    string                 `protobuf:"bytes,6,opt,name=visibility,proto3" json:"visibility,omitempty"`
	Engine        string                 `protobuf:"bytes,7,opt,name=engine,proto3" json:"engine,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tags          map[string]string      `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataChart) Reset() {
	*x = MetadataChart{}
	mi := &file_starmap_model_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataChart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataChart) ProtoMessage() {}

func (x *MetadataChart) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_model_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataChart.ProtoReflect.Descriptor instead.
func (*MetadataChart) Descriptor() ([]byte, []int) {
	return file_starmap_model_proto_rawDescGZIP(), []int{16}
}

func (x *MetadataChart) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MetadataChart) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetadataChart) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *MetadataChart) GetMaintainer() string {
	if x != nil {
		return x.Maintainer
	}
	return ""
}

func (x *MetadataChart) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MetadataChart) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *MetadataChart) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *MetadataChart) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *MetadataChart) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type StarChart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	SchemaVersion string                 `protobuf:"bytes,2,opt,name=schemaVersion,proto3" json:"schemaVersion,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Metadata      *MetadataChart         `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Chart         *Chart                 `protobuf:"bytes,5,opt,name=chart,proto3" json:"chart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StarChart) Reset() {
	*x = StarChart{}
	mi := &file_starmap_model_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StarChart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarChart) ProtoMessage() {}

func (x *StarChart) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_model_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarChart.ProtoReflect.Descriptor instead.
func (*StarChart) Descriptor() ([]byte, []int) {
	return file_starmap_model_proto_rawDescGZIP(), []int{17}
}

func (x *StarChart) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *StarChart) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *StarChart) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *StarChart) GetMetadata() *MetadataChart {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *StarChart) GetChart() *Chart {
	if x != nil {
		return x.Chart
	}
	return nil
}

type CommandLink_CommandLinkMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        string                 `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandLink_CommandLinkMetadata) Reset() {
	*x = CommandLink_CommandLinkMetadata{}
	mi := &file_starmap_model_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandLink_CommandLinkMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandLink_CommandLinkMetadata) ProtoMessage() {}

func (x *CommandLink_CommandLinkMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_model_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandLink_CommandLinkMetadata.ProtoReflect.Descriptor instead.
func (*CommandLink_CommandLinkMetadata) Descriptor() ([]byte, []int) {
	return file_starmap_model_proto_rawDescGZIP(), []int{3, 0}
}

func (x *CommandLink_CommandLinkMetadata) GetParams() string {
	if x != nil {
		return x.Params
	}
	return ""
}

func (x *CommandLink_CommandLinkMetadata) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CommandLink_CommandLinkMetadata) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type EntrypointLink_EntrypointLinkMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntrypointLink_EntrypointLinkMetadata) Reset() {
	*x = EntrypointLink_EntrypointLinkMetadata{}
	mi := &file_starmap_model_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntrypointLink_EntrypointLinkMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntrypointLink_EntrypointLinkMetadata) ProtoMessage() {}

func (x *EntrypointLink_EntrypointLinkMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_model_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntrypointLink_EntrypointLinkMetadata.ProtoReflect.Descriptor instead.
func (*EntrypointLink_EntrypointLinkMetadata) Descriptor() ([]byte, []int) {
	return file_starmap_model_proto_rawDescGZIP(), []int{4, 0}
}

func (x *EntrypointLink_EntrypointLinkMetadata) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *EntrypointLink_EntrypointLinkMetadata) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type RunLink_RunLinkMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunLink_RunLinkMetadata) Reset() {
	*x = RunLink_RunLinkMetadata{}
	mi := &file_starmap_model_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunLink_RunLinkMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunLink_RunLinkMetadata) ProtoMessage() {}

func (x *RunLink_RunLinkMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_model_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunLink_RunLinkMetadata.ProtoReflect.Descriptor instead.
func (*RunLink_RunLinkMetadata) Descriptor() ([]byte, []int) {
	return file_starmap_model_proto_rawDescGZIP(), []int{5, 0}
}

func (x *RunLink_RunLinkMetadata) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_starmap_model_proto protoreflect.FileDescriptor

const file_starmap_model_proto_rawDesc = "" +
	"\n" +
	"\x13starmap_model.proto\x12\x05proto\"\x0e\n" +
	"\fEmptyMessage\"\xa6\x01\n" +
	"\x0fEntrypointLinks\x12.\n" +
	"\acommand\x18\x01 \x01(\v2\x12.proto.CommandLinkH\x00R\acommand\x127\n" +
	"\n" +
	"entrypoint\x18\x02 \x01(\v2\x15.proto.EntrypointLinkH\x00R\n" +
	"entrypoint\x12\"\n" +
	"\x03run\x18\x03 \x01(\v2\x0e.proto.RunLinkH\x00R\x03runB\x06\n" +
	"\x04link\"\xbe\x01\n" +
	"\n" +
	"Entrypoint\x12+\n" +
	"\bmetadata\x18\x01 \x01(\v2\x0f.proto.MetadataR\bmetadata\x12(\n" +
	"\acontrol\x18\x02 \x01(\v2\x0e.proto.ControlR\acontrol\x12+\n" +
	"\bfeatures\x18\x03 \x01(\v2\x0f.proto.FeaturesR\bfeatures\x12,\n" +
	"\x05links\x18\x04 \x01(\v2\x16.proto.EntrypointLinksR\x05links\"\xca\x01\n" +
	"\vCommandLink\x12B\n" +
	"\bmetadata\x18\x01 \x01(\v2&.proto.CommandLink.CommandLinkMetadataR\bmetadata\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x1aU\n" +
	"\x13CommandLinkMetadata\x12\x16\n" +
	"\x06params\x18\x01 \x01(\tR\x06params\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"\xbe\x01\n" +
	"\x0eEntrypointLink\x12H\n" +
	"\bmetadata\x18\x01 \x01(\v2,.proto.EntrypointLink.EntrypointLinkMetadataR\bmetadata\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x1a@\n" +
	"\x16EntrypointLinkMetadata\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"\x92\x01\n" +
	"\aRunLink\x12:\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1e.proto.RunLink.RunLinkMetadataR\bmetadata\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x1a)\n" +
	"\x0fRunLinkMetadata\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"\xfa\x02\n" +
	"\n" +
	"DataSource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\"\n" +
	"\fresourceName\x18\x05 \x01(\tR\fresourceName\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x125\n" +
	"\x06labels\x18\a \x03(\v2\x1d.proto.DataSource.LabelsEntryR\x06labels\x12/\n" +
	"\x04tags\x18\b \x03(\v2\x1b.proto.DataSource.TagsEntryR\x04tags\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x90\x03\n" +
	"\bMetadata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\"\n" +
	"\x05build\x18\x04 \x01(\v2\f.proto.BuildR\x05build\x12\x16\n" +
	"\x06prefix\x18\x05 \x01(\tR\x06prefix\x12\x14\n" +
	"\x05topic\x18\x06 \x01(\tR\x05topic\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x123\n" +
	"\x06labels\x18\b \x03(\v2\x1b.proto.Metadata.LabelsEntryR\x06labels\x12-\n" +
	"\x04tags\x18\t \x03(\v2\x19.proto.Metadata.TagsEntryR\x04tags\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"O\n" +
	"\x05Build\x12\x12\n" +
	"\x04pull\x18\x01 \x01(\tR\x04pull\x12\x18\n" +
	"\aworkdir\x18\x02 \x01(\tR\aworkdir\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\"\xbd\x01\n" +
	"\aControl\x124\n" +
	"\x15disableVirtualization\x18\x01 \x01(\bR\x15disableVirtualization\x12 \n" +
	"\vrunDetached\x18\x02 \x01(\bR\vrunDetached\x12\"\n" +
	"\fremoveOnStop\x18\x03 \x01(\bR\fremoveOnStop\x12\x16\n" +
	"\x06memory\x18\x04 \x01(\tR\x06memory\x12\x1e\n" +
	"\n" +
	"kernelArgs\x18\x05 \x01(\tR\n" +
	"kernelArgs\"\x8a\x01\n" +
	"\bFeatures\x12\x1a\n" +
	"\bnetworks\x18\x01 \x03(\tR\bnetworks\x12\x14\n" +
	"\x05ports\x18\x02 \x03(\tR\x05ports\x12\x18\n" +
	"\avolumes\x18\x03 \x03(\tR\avolumes\x12\x18\n" +
	"\atargets\x18\x04 \x03(\tR\atargets\x12\x18\n" +
	"\aenvVars\x18\x05 \x03(\tR\aenvVars\"c\n" +
	"\x05Links\x12\x1c\n" +
	"\tsoftLinks\x18\x01 \x03(\tR\tsoftLinks\x12\x1c\n" +
	"\thardLinks\x18\x02 \x03(\tR\thardLinks\x12\x1e\n" +
	"\n" +
	"eventLinks\x18\x03 \x03(\tR\n" +
	"eventLinks\"\xb9\x01\n" +
	"\x0fStoredProcedure\x12+\n" +
	"\bmetadata\x18\x01 \x01(\v2\x0f.proto.MetadataR\bmetadata\x12(\n" +
	"\acontrol\x18\x02 \x01(\v2\x0e.proto.ControlR\acontrol\x12+\n" +
	"\bfeatures\x18\x03 \x01(\v2\x0f.proto.FeaturesR\bfeatures\x12\"\n" +
	"\x05links\x18\x04 \x01(\v2\f.proto.LinksR\x05links\"\x8b\x01\n" +
	"\x05Event\x12+\n" +
	"\bmetadata\x18\x01 \x01(\v2\x0f.proto.MetadataR\bmetadata\x12(\n" +
	"\acontrol\x18\x02 \x01(\v2\x0e.proto.ControlR\acontrol\x12+\n" +
	"\bfeatures\x18\x03 \x01(\v2\x0f.proto.FeaturesR\bfeatures\"\xb6\x01\n" +
	"\fEventTrigger\x12+\n" +
	"\bmetadata\x18\x01 \x01(\v2\x0f.proto.MetadataR\bmetadata\x12(\n" +
	"\acontrol\x18\x02 \x01(\v2\x0e.proto.ControlR\acontrol\x12+\n" +
	"\bfeatures\x18\x03 \x01(\v2\x0f.proto.FeaturesR\bfeatures\x12\"\n" +
	"\x05links\x18\x04 \x01(\v2\f.proto.LinksR\x05links\"\xf5\x05\n" +
	"\x05Chart\x12?\n" +
	"\vdataSources\x18\x01 \x03(\v2\x1d.proto.Chart.DataSourcesEntryR\vdataSources\x12N\n" +
	"\x10storedProcedures\x18\x02 \x03(\v2\".proto.Chart.StoredProceduresEntryR\x10storedProcedures\x12E\n" +
	"\reventTriggers\x18\x03 \x03(\v2\x1f.proto.Chart.EventTriggersEntryR\reventTriggers\x120\n" +
	"\x06events\x18\x04 \x03(\v2\x18.proto.Chart.EventsEntryR\x06events\x12?\n" +
	"\ventrypoints\x18\x05 \x03(\v2\x1d.proto.Chart.EntrypointsEntryR\ventrypoints\x1aQ\n" +
	"\x10DataSourcesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.proto.DataSourceR\x05value:\x028\x01\x1a[\n" +
	"\x15StoredProceduresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.proto.StoredProcedureR\x05value:\x028\x01\x1aU\n" +
	"\x12EventTriggersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.proto.EventTriggerR\x05value:\x028\x01\x1aG\n" +
	"\vEventsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\"\n" +
	"\x05value\x18\x02 \x01(\v2\f.proto.EventR\x05value:\x028\x01\x1aQ\n" +
	"\x10EntrypointsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.proto.EntrypointR\x05value:\x028\x01\"\xad\x03\n" +
	"\rMetadataChart\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"maintainer\x18\x04 \x01(\tR\n" +
	"maintainer\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"visibility\x18\x06 \x01(\tR\n" +
	"visibility\x12\x16\n" +
	"\x06engine\x18\a \x01(\tR\x06engine\x128\n" +
	"\x06labels\x18\b \x03(\v2 .proto.MetadataChart.LabelsEntryR\x06labels\x122\n" +
	"\x04tags\x18\t \x03(\v2\x1e.proto.MetadataChart.TagsEntryR\x04tags\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbb\x01\n" +
	"\tStarChart\x12\x1e\n" +
	"\n" +
	"apiVersion\x18\x01 \x01(\tR\n" +
	"apiVersion\x12$\n" +
	"\rschemaVersion\x18\x02 \x01(\tR\rschemaVersion\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x120\n" +
	"\bmetadata\x18\x04 \x01(\v2\x14.proto.MetadataChartR\bmetadata\x12\"\n" +
	"\x05chart\x18\x05 \x01(\v2\f.proto.ChartR\x05chartB\x1dZ\x1bgithub.com/c12s/starmap/apib\x06proto3"

var (
	file_starmap_model_proto_rawDescOnce sync.Once
	file_starmap_model_proto_rawDescData []byte
)

func file_starmap_model_proto_rawDescGZIP() []byte {
	file_starmap_model_proto_rawDescOnce.Do(func() {
		file_starmap_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_starmap_model_proto_rawDesc), len(file_starmap_model_proto_rawDesc)))
	})
	return file_starmap_model_proto_rawDescData
}

var file_starmap_model_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_starmap_model_proto_goTypes = []any{
	(*EmptyMessage)(nil),                    // 0: proto.EmptyMessage
	(*EntrypointLinks)(nil),                 // 1: proto.EntrypointLinks
	(*Entrypoint)(nil),                      // 2: proto.Entrypoint
	(*CommandLink)(nil),                     // 3: proto.CommandLink
	(*EntrypointLink)(nil),                  // 4: proto.EntrypointLink
	(*RunLink)(nil),                         // 5: proto.RunLink
	(*DataSource)(nil),                      // 6: proto.DataSource
	(*Metadata)(nil),                        // 7: proto.Metadata
	(*Build)(nil),                           // 8: proto.Build
	(*Control)(nil),                         // 9: proto.Control
	(*Features)(nil),                        // 10: proto.Features
	(*Links)(nil),                           // 11: proto.Links
	(*StoredProcedure)(nil),                 // 12: proto.StoredProcedure
	(*Event)(nil),                           // 13: proto.Event
	(*EventTrigger)(nil),                    // 14: proto.EventTrigger
	(*Chart)(nil),                           // 15: proto.Chart
	(*MetadataChart)(nil),                   // 16: proto.MetadataChart
	(*StarChart)(nil),                       // 17: proto.StarChart
	(*CommandLink_CommandLinkMetadata)(nil), // 18: proto.CommandLink.CommandLinkMetadata
	(*EntrypointLink_EntrypointLinkMetadata)(nil), // 19: proto.EntrypointLink.EntrypointLinkMetadata
	(*RunLink_RunLinkMetadata)(nil),               // 20: proto.RunLink.RunLinkMetadata
	nil,                                           // 21: proto.DataSource.LabelsEntry
	nil,                                           // 22: proto.DataSource.TagsEntry
	nil,                                           // 23: proto.Metadata.LabelsEntry
	nil,                                           // 24: proto.Metadata.TagsEntry
	nil,                                           // 25: proto.Chart.DataSourcesEntry
	nil,                                           // 26: proto.Chart.StoredProceduresEntry
	nil,                                           // 27: proto.Chart.EventTriggersEntry
	nil,                                           // 28: proto.Chart.EventsEntry
	nil,                                           // 29: proto.Chart.EntrypointsEntry
	nil,                                           // 30: proto.MetadataChart.LabelsEntry
	nil,                                           // 31: proto.MetadataChart.TagsEntry
}
var file_starmap_model_proto_depIdxs = []int32{
	3,  // 0: proto.EntrypointLinks.command:type_name -> proto.CommandLink
	4,  // 1: proto.EntrypointLinks.entrypoint:type_name -> proto.EntrypointLink
	5,  // 2: proto.EntrypointLinks.run:type_name -> proto.RunLink
	7,  // 3: proto.Entrypoint.metadata:type_name -> proto.Metadata
	9,  // 4: proto.Entrypoint.control:type_name -> proto.Control
	10, // 5: proto.Entrypoint.features:type_name -> proto.Features
	1,  // 6: proto.Entrypoint.links:type_name -> proto.EntrypointLinks
	18, // 7: proto.CommandLink.metadata:type_name -> proto.CommandLink.CommandLinkMetadata
	19, // 8: proto.EntrypointLink.metadata:type_name -> proto.EntrypointLink.EntrypointLinkMetadata
	20, // 9: proto.RunLink.metadata:type_name -> proto.RunLink.RunLinkMetadata
	21, // 10: proto.DataSource.labels:type_name -> proto.DataSource.LabelsEntry
	22, // 11: proto.DataSource.tags:type_name -> proto.DataSource.TagsEntry
	8,  // 12: proto.Metadata.build:type_name -> proto.Build
	23, // 13: proto.Metadata.labels:type_name -> proto.Metadata.LabelsEntry
	24, // 14: proto.Metadata.tags:type_name -> proto.Metadata.TagsEntry
	7,  // 15: proto.StoredProcedure.metadata:type_name -> proto.Metadata
	9,  // 16: proto.StoredProcedure.control:type_name -> proto.Control
	10, // 17: proto.StoredProcedure.features:type_name -> proto.Features
	11, // 18: proto.StoredProcedure.links:type_name -> proto.Links
	7,  // 19: proto.Event.metadata:type_name -> proto.Metadata
	9,  // 20: proto.Event.control:type_name -> proto.Control
	10, // 21: proto.Event.features:type_name -> proto.Features
	7,  // 22: proto.EventTrigger.metadata:type_name -> proto.Metadata
	9,  // 23: proto.EventTrigger.control:type_name -> proto.Control
	10, // 24: proto.EventTrigger.features:type_name -> proto.Features
	11, // 25: proto.EventTrigger.links:type_name -> proto.Links
	25, // 26: proto.Chart.dataSources:type_name -> proto.Chart.DataSourcesEntry
	26, // 27: proto.Chart.storedProcedures:type_name -> proto.Chart.StoredProceduresEntry
	27, // 28: proto.Chart.eventTriggers:type_name -> proto.Chart.EventTriggersEntry
	28, // 29: proto.Chart.events:type_name -> proto.Chart.EventsEntry
	29, // 30: proto.Chart.entrypoints:type_name -> proto.Chart.EntrypointsEntry
	30, // 31: proto.MetadataChart.labels:type_name -> proto.MetadataChart.LabelsEntry
	31, // 32: proto.MetadataChart.tags:type_name -> proto.MetadataChart.TagsEntry
	16, // 33: proto.StarChart.metadata:type_name -> proto.MetadataChart
	15, // 34: proto.StarChart.chart:type_name -> proto.Chart
	6,  // 35: proto.Chart.DataSourcesEntry.value:type_name -> proto.DataSource
	12, // 36: proto.Chart.StoredProceduresEntry.value:type_name -> proto.StoredProcedure
	14, // 37: proto.Chart.EventTriggersEntry.value:type_name -> proto.EventTrigger
	13, // 38: proto.Chart.EventsEntry.value:type_name -> proto.Event
	2,  // 39: proto.Chart.EntrypointsEntry.value:type_name -> proto.Entrypoint
	40, // [40:40] is the sub-list for method output_type
	40, // [40:40] is the sub-list for method input_type
	40, // [40:40] is the sub-list for extension type_name
	40, // [40:40] is the sub-list for extension extendee
	0,  // [0:40] is the sub-list for field type_name
}

func init() { file_starmap_model_proto_init() }
func file_starmap_model_proto_init() {
	if File_starmap_model_proto != nil {
		return
	}
	file_starmap_model_proto_msgTypes[1].OneofWrappers = []any{
		(*EntrypointLinks_Command)(nil),
		(*EntrypointLinks_Entrypoint)(nil),
		(*EntrypointLinks_Run)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_starmap_model_proto_rawDesc), len(file_starmap_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_starmap_model_proto_goTypes,
		DependencyIndexes: file_starmap_model_proto_depIdxs,
		MessageInfos:      file_starmap_model_proto_msgTypes,
	}.Build()
	File_starmap_model_proto = out.File
	file_starmap_model_proto_goTypes = nil
	file_starmap_model_proto_depIdxs = nil
}
