// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: starmap.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RegistryService_PutChart_FullMethodName         = "/proto.RegistryService/PutChart"
	RegistryService_GetChartMetadata_FullMethodName = "/proto.RegistryService/GetChartMetadata"
	RegistryService_GetChartsLabels_FullMethodName  = "/proto.RegistryService/GetChartsLabels"
	RegistryService_GetChartId_FullMethodName       = "/proto.RegistryService/GetChartId"
	RegistryService_GetMissingLayers_FullMethodName = "/proto.RegistryService/GetMissingLayers"
	RegistryService_DeleteChart_FullMethodName      = "/proto.RegistryService/DeleteChart"
	RegistryService_UpdateChart_FullMethodName      = "/proto.RegistryService/UpdateChart"
	RegistryService_SwitchCheckpoint_FullMethodName = "/proto.RegistryService/SwitchCheckpoint"
	RegistryService_Timeline_FullMethodName         = "/proto.RegistryService/Timeline"
)

// RegistryServiceClient is the client API for RegistryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RegistryServiceClient interface {
	PutChart(ctx context.Context, in *StarChart, opts ...grpc.CallOption) (*PutChartResp, error)
	GetChartMetadata(ctx context.Context, in *GetChartFromMetadataReq, opts ...grpc.CallOption) (*GetChartResp, error)
	GetChartsLabels(ctx context.Context, in *GetChartsLabelsReq, opts ...grpc.CallOption) (*GetChartsLabelsResp, error)
	GetChartId(ctx context.Context, in *GetChartIdReq, opts ...grpc.CallOption) (*GetChartResp, error)
	GetMissingLayers(ctx context.Context, in *GetMissingLayersReq, opts ...grpc.CallOption) (*GetMissingLayersResp, error)
	DeleteChart(ctx context.Context, in *DeleteChartReq, opts ...grpc.CallOption) (*EmptyMessage, error)
	UpdateChart(ctx context.Context, in *StarChart, opts ...grpc.CallOption) (*PutChartResp, error)
	SwitchCheckpoint(ctx context.Context, in *SwitchCheckpointReq, opts ...grpc.CallOption) (*SwitchCheckpointResp, error)
	Timeline(ctx context.Context, in *TimelineReq, opts ...grpc.CallOption) (*TimelineResp, error)
}

type registryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRegistryServiceClient(cc grpc.ClientConnInterface) RegistryServiceClient {
	return &registryServiceClient{cc}
}

func (c *registryServiceClient) PutChart(ctx context.Context, in *StarChart, opts ...grpc.CallOption) (*PutChartResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutChartResp)
	err := c.cc.Invoke(ctx, RegistryService_PutChart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryServiceClient) GetChartMetadata(ctx context.Context, in *GetChartFromMetadataReq, opts ...grpc.CallOption) (*GetChartResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChartResp)
	err := c.cc.Invoke(ctx, RegistryService_GetChartMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryServiceClient) GetChartsLabels(ctx context.Context, in *GetChartsLabelsReq, opts ...grpc.CallOption) (*GetChartsLabelsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChartsLabelsResp)
	err := c.cc.Invoke(ctx, RegistryService_GetChartsLabels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryServiceClient) GetChartId(ctx context.Context, in *GetChartIdReq, opts ...grpc.CallOption) (*GetChartResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChartResp)
	err := c.cc.Invoke(ctx, RegistryService_GetChartId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryServiceClient) GetMissingLayers(ctx context.Context, in *GetMissingLayersReq, opts ...grpc.CallOption) (*GetMissingLayersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMissingLayersResp)
	err := c.cc.Invoke(ctx, RegistryService_GetMissingLayers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryServiceClient) DeleteChart(ctx context.Context, in *DeleteChartReq, opts ...grpc.CallOption) (*EmptyMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyMessage)
	err := c.cc.Invoke(ctx, RegistryService_DeleteChart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryServiceClient) UpdateChart(ctx context.Context, in *StarChart, opts ...grpc.CallOption) (*PutChartResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutChartResp)
	err := c.cc.Invoke(ctx, RegistryService_UpdateChart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryServiceClient) SwitchCheckpoint(ctx context.Context, in *SwitchCheckpointReq, opts ...grpc.CallOption) (*SwitchCheckpointResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SwitchCheckpointResp)
	err := c.cc.Invoke(ctx, RegistryService_SwitchCheckpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryServiceClient) Timeline(ctx context.Context, in *TimelineReq, opts ...grpc.CallOption) (*TimelineResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TimelineResp)
	err := c.cc.Invoke(ctx, RegistryService_Timeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistryServiceServer is the server API for RegistryService service.
// All implementations must embed UnimplementedRegistryServiceServer
// for forward compatibility.
type RegistryServiceServer interface {
	PutChart(context.Context, *StarChart) (*PutChartResp, error)
	GetChartMetadata(context.Context, *GetChartFromMetadataReq) (*GetChartResp, error)
	GetChartsLabels(context.Context, *GetChartsLabelsReq) (*GetChartsLabelsResp, error)
	GetChartId(context.Context, *GetChartIdReq) (*GetChartResp, error)
	GetMissingLayers(context.Context, *GetMissingLayersReq) (*GetMissingLayersResp, error)
	DeleteChart(context.Context, *DeleteChartReq) (*EmptyMessage, error)
	UpdateChart(context.Context, *StarChart) (*PutChartResp, error)
	SwitchCheckpoint(context.Context, *SwitchCheckpointReq) (*SwitchCheckpointResp, error)
	Timeline(context.Context, *TimelineReq) (*TimelineResp, error)
	mustEmbedUnimplementedRegistryServiceServer()
}

// UnimplementedRegistryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRegistryServiceServer struct{}

func (UnimplementedRegistryServiceServer) PutChart(context.Context, *StarChart) (*PutChartResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutChart not implemented")
}
func (UnimplementedRegistryServiceServer) GetChartMetadata(context.Context, *GetChartFromMetadataReq) (*GetChartResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChartMetadata not implemented")
}
func (UnimplementedRegistryServiceServer) GetChartsLabels(context.Context, *GetChartsLabelsReq) (*GetChartsLabelsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChartsLabels not implemented")
}
func (UnimplementedRegistryServiceServer) GetChartId(context.Context, *GetChartIdReq) (*GetChartResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChartId not implemented")
}
func (UnimplementedRegistryServiceServer) GetMissingLayers(context.Context, *GetMissingLayersReq) (*GetMissingLayersResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMissingLayers not implemented")
}
func (UnimplementedRegistryServiceServer) DeleteChart(context.Context, *DeleteChartReq) (*EmptyMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteChart not implemented")
}
func (UnimplementedRegistryServiceServer) UpdateChart(context.Context, *StarChart) (*PutChartResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateChart not implemented")
}
func (UnimplementedRegistryServiceServer) SwitchCheckpoint(context.Context, *SwitchCheckpointReq) (*SwitchCheckpointResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SwitchCheckpoint not implemented")
}
func (UnimplementedRegistryServiceServer) Timeline(context.Context, *TimelineReq) (*TimelineResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Timeline not implemented")
}
func (UnimplementedRegistryServiceServer) mustEmbedUnimplementedRegistryServiceServer() {}
func (UnimplementedRegistryServiceServer) testEmbeddedByValue()                         {}

// UnsafeRegistryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegistryServiceServer will
// result in compilation errors.
type UnsafeRegistryServiceServer interface {
	mustEmbedUnimplementedRegistryServiceServer()
}

func RegisterRegistryServiceServer(s grpc.ServiceRegistrar, srv RegistryServiceServer) {
	// If the following call pancis, it indicates UnimplementedRegistryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RegistryService_ServiceDesc, srv)
}

func _RegistryService_PutChart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StarChart)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).PutChart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryService_PutChart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).PutChart(ctx, req.(*StarChart))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryService_GetChartMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChartFromMetadataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).GetChartMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryService_GetChartMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).GetChartMetadata(ctx, req.(*GetChartFromMetadataReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryService_GetChartsLabels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChartsLabelsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).GetChartsLabels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryService_GetChartsLabels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).GetChartsLabels(ctx, req.(*GetChartsLabelsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryService_GetChartId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChartIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).GetChartId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryService_GetChartId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).GetChartId(ctx, req.(*GetChartIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryService_GetMissingLayers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMissingLayersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).GetMissingLayers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryService_GetMissingLayers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).GetMissingLayers(ctx, req.(*GetMissingLayersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryService_DeleteChart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteChartReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).DeleteChart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryService_DeleteChart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).DeleteChart(ctx, req.(*DeleteChartReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryService_UpdateChart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StarChart)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).UpdateChart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryService_UpdateChart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).UpdateChart(ctx, req.(*StarChart))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryService_SwitchCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SwitchCheckpointReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).SwitchCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryService_SwitchCheckpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).SwitchCheckpoint(ctx, req.(*SwitchCheckpointReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryService_Timeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimelineReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).Timeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryService_Timeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).Timeline(ctx, req.(*TimelineReq))
	}
	return interceptor(ctx, in, info, handler)
}

// RegistryService_ServiceDesc is the grpc.ServiceDesc for RegistryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RegistryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.RegistryService",
	HandlerType: (*RegistryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutChart",
			Handler:    _RegistryService_PutChart_Handler,
		},
		{
			MethodName: "GetChartMetadata",
			Handler:    _RegistryService_GetChartMetadata_Handler,
		},
		{
			MethodName: "GetChartsLabels",
			Handler:    _RegistryService_GetChartsLabels_Handler,
		},
		{
			MethodName: "GetChartId",
			Handler:    _RegistryService_GetChartId_Handler,
		},
		{
			MethodName: "GetMissingLayers",
			Handler:    _RegistryService_GetMissingLayers_Handler,
		},
		{
			MethodName: "DeleteChart",
			Handler:    _RegistryService_DeleteChart_Handler,
		},
		{
			MethodName: "UpdateChart",
			Handler:    _RegistryService_UpdateChart_Handler,
		},
		{
			MethodName: "SwitchCheckpoint",
			Handler:    _RegistryService_SwitchCheckpoint_Handler,
		},
		{
			MethodName: "Timeline",
			Handler:    _RegistryService_Timeline_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "starmap.proto",
}
