// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: starmap.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMissingLayersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	SchemaVersion string                 `protobuf:"bytes,2,opt,name=schemaVersion,proto3" json:"schemaVersion,omitempty"`
	ChartId       string                 `protobuf:"bytes,3,opt,name=chartId,proto3" json:"chartId,omitempty"`
	Namespace     string                 `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Maintainer    string                 `protobuf:"bytes,5,opt,name=maintainer,proto3" json:"maintainer,omitempty"`
	Layers        []string               `protobuf:"bytes,6,rep,name=layers,proto3" json:"layers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMissingLayersReq) Reset() {
	*x = GetMissingLayersReq{}
	mi := &file_starmap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMissingLayersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMissingLayersReq) ProtoMessage() {}

func (x *GetMissingLayersReq) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMissingLayersReq.ProtoReflect.Descriptor instead.
func (*GetMissingLayersReq) Descriptor() ([]byte, []int) {
	return file_starmap_proto_rawDescGZIP(), []int{0}
}

func (x *GetMissingLayersReq) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *GetMissingLayersReq) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *GetMissingLayersReq) GetChartId() string {
	if x != nil {
		return x.ChartId
	}
	return ""
}

func (x *GetMissingLayersReq) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetMissingLayersReq) GetMaintainer() string {
	if x != nil {
		return x.Maintainer
	}
	return ""
}

func (x *GetMissingLayersReq) GetLayers() []string {
	if x != nil {
		return x.Layers
	}
	return nil
}

type GetMissingLayersResp struct {
	state            protoimpl.MessageState      `protogen:"open.v1"`
	ChartId          string                      `protobuf:"bytes,1,opt,name=chartId,proto3" json:"chartId,omitempty"`
	Namespace        string                      `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Maintainer       string                      `protobuf:"bytes,3,opt,name=maintainer,proto3" json:"maintainer,omitempty"`
	ApiVersion       string                      `protobuf:"bytes,4,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	SchemaVersion    string                      `protobuf:"bytes,5,opt,name=schemaVersion,proto3" json:"schemaVersion,omitempty"`
	DataSources      map[string]*DataSource      `protobuf:"bytes,6,rep,name=dataSources,proto3" json:"dataSources,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StoredProcedures map[string]*StoredProcedure `protobuf:"bytes,7,rep,name=storedProcedures,proto3" json:"storedProcedures,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	EventTriggers    map[string]*EventTrigger    `protobuf:"bytes,8,rep,name=eventTriggers,proto3" json:"eventTriggers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Events           map[string]*Event           `protobuf:"bytes,9,rep,name=events,proto3" json:"events,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetMissingLayersResp) Reset() {
	*x = GetMissingLayersResp{}
	mi := &file_starmap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMissingLayersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMissingLayersResp) ProtoMessage() {}

func (x *GetMissingLayersResp) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMissingLayersResp.ProtoReflect.Descriptor instead.
func (*GetMissingLayersResp) Descriptor() ([]byte, []int) {
	return file_starmap_proto_rawDescGZIP(), []int{1}
}

func (x *GetMissingLayersResp) GetChartId() string {
	if x != nil {
		return x.ChartId
	}
	return ""
}

func (x *GetMissingLayersResp) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetMissingLayersResp) GetMaintainer() string {
	if x != nil {
		return x.Maintainer
	}
	return ""
}

func (x *GetMissingLayersResp) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *GetMissingLayersResp) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *GetMissingLayersResp) GetDataSources() map[string]*DataSource {
	if x != nil {
		return x.DataSources
	}
	return nil
}

func (x *GetMissingLayersResp) GetStoredProcedures() map[string]*StoredProcedure {
	if x != nil {
		return x.StoredProcedures
	}
	return nil
}

func (x *GetMissingLayersResp) GetEventTriggers() map[string]*EventTrigger {
	if x != nil {
		return x.EventTriggers
	}
	return nil
}

func (x *GetMissingLayersResp) GetEvents() map[string]*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type GetChartIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	SchemaVersion string                 `protobuf:"bytes,2,opt,name=schemaVersion,proto3" json:"schemaVersion,omitempty"`
	ChartId       string                 `protobuf:"bytes,3,opt,name=chartId,proto3" json:"chartId,omitempty"`
	Namespace     string                 `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Maintainer    string                 `protobuf:"bytes,5,opt,name=maintainer,proto3" json:"maintainer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChartIdReq) Reset() {
	*x = GetChartIdReq{}
	mi := &file_starmap_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChartIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChartIdReq) ProtoMessage() {}

func (x *GetChartIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChartIdReq.ProtoReflect.Descriptor instead.
func (*GetChartIdReq) Descriptor() ([]byte, []int) {
	return file_starmap_proto_rawDescGZIP(), []int{2}
}

func (x *GetChartIdReq) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *GetChartIdReq) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *GetChartIdReq) GetChartId() string {
	if x != nil {
		return x.ChartId
	}
	return ""
}

func (x *GetChartIdReq) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetChartIdReq) GetMaintainer() string {
	if x != nil {
		return x.Maintainer
	}
	return ""
}

type DeleteChartReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Maintainer    string                 `protobuf:"bytes,4,opt,name=maintainer,proto3" json:"maintainer,omitempty"`
	ApiVersion    string                 `protobuf:"bytes,5,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	SchemaVersion string                 `protobuf:"bytes,6,opt,name=schemaVersion,proto3" json:"schemaVersion,omitempty"`
	Kind          string                 `protobuf:"bytes,7,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChartReq) Reset() {
	*x = DeleteChartReq{}
	mi := &file_starmap_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChartReq) ProtoMessage() {}

func (x *DeleteChartReq) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChartReq.ProtoReflect.Descriptor instead.
func (*DeleteChartReq) Descriptor() ([]byte, []int) {
	return file_starmap_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteChartReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteChartReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteChartReq) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DeleteChartReq) GetMaintainer() string {
	if x != nil {
		return x.Maintainer
	}
	return ""
}

func (x *DeleteChartReq) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *DeleteChartReq) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *DeleteChartReq) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type GetChartsLabelsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	SchemaVersion string                 `protobuf:"bytes,2,opt,name=schemaVersion,proto3" json:"schemaVersion,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Maintainer    string                 `protobuf:"bytes,4,opt,name=maintainer,proto3" json:"maintainer,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChartsLabelsReq) Reset() {
	*x = GetChartsLabelsReq{}
	mi := &file_starmap_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChartsLabelsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChartsLabelsReq) ProtoMessage() {}

func (x *GetChartsLabelsReq) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChartsLabelsReq.ProtoReflect.Descriptor instead.
func (*GetChartsLabelsReq) Descriptor() ([]byte, []int) {
	return file_starmap_proto_rawDescGZIP(), []int{4}
}

func (x *GetChartsLabelsReq) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *GetChartsLabelsReq) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *GetChartsLabelsReq) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetChartsLabelsReq) GetMaintainer() string {
	if x != nil {
		return x.Maintainer
	}
	return ""
}

func (x *GetChartsLabelsReq) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type GetChartsLabelsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Charts        []*GetChartResp        `protobuf:"bytes,1,rep,name=charts,proto3" json:"charts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChartsLabelsResp) Reset() {
	*x = GetChartsLabelsResp{}
	mi := &file_starmap_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChartsLabelsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChartsLabelsResp) ProtoMessage() {}

func (x *GetChartsLabelsResp) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChartsLabelsResp.ProtoReflect.Descriptor instead.
func (*GetChartsLabelsResp) Descriptor() ([]byte, []int) {
	return file_starmap_proto_rawDescGZIP(), []int{5}
}

func (x *GetChartsLabelsResp) GetCharts() []*GetChartResp {
	if x != nil {
		return x.Charts
	}
	return nil
}

type GetChartFromMetadataReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Maintainer    string                 `protobuf:"bytes,3,opt,name=maintainer,proto3" json:"maintainer,omitempty"`
	ApiVersion    string                 `protobuf:"bytes,4,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	SchemaVersion string                 `protobuf:"bytes,5,opt,name=schemaVersion,proto3" json:"schemaVersion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChartFromMetadataReq) Reset() {
	*x = GetChartFromMetadataReq{}
	mi := &file_starmap_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChartFromMetadataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChartFromMetadataReq) ProtoMessage() {}

func (x *GetChartFromMetadataReq) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChartFromMetadataReq.ProtoReflect.Descriptor instead.
func (*GetChartFromMetadataReq) Descriptor() ([]byte, []int) {
	return file_starmap_proto_rawDescGZIP(), []int{6}
}

func (x *GetChartFromMetadataReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetChartFromMetadataReq) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetChartFromMetadataReq) GetMaintainer() string {
	if x != nil {
		return x.Maintainer
	}
	return ""
}

func (x *GetChartFromMetadataReq) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *GetChartFromMetadataReq) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

type GetChartResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	SchemaVersion string                 `protobuf:"bytes,2,opt,name=schemaVersion,proto3" json:"schemaVersion,omitempty"`
	Metadata      *MetadataChart         `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Chart         *Chart                 `protobuf:"bytes,4,opt,name=chart,proto3" json:"chart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChartResp) Reset() {
	*x = GetChartResp{}
	mi := &file_starmap_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChartResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChartResp) ProtoMessage() {}

func (x *GetChartResp) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChartResp.ProtoReflect.Descriptor instead.
func (*GetChartResp) Descriptor() ([]byte, []int) {
	return file_starmap_proto_rawDescGZIP(), []int{7}
}

func (x *GetChartResp) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *GetChartResp) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *GetChartResp) GetMetadata() *MetadataChart {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetChartResp) GetChart() *Chart {
	if x != nil {
		return x.Chart
	}
	return nil
}

type PutChartResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ApiVersion    string                 `protobuf:"bytes,2,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	SchemaVersion string                 `protobuf:"bytes,3,opt,name=schemaVersion,proto3" json:"schemaVersion,omitempty"`
	Kind          string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,6,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Maintainer    string                 `protobuf:"bytes,7,opt,name=maintainer,proto3" json:"maintainer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutChartResp) Reset() {
	*x = PutChartResp{}
	mi := &file_starmap_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutChartResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutChartResp) ProtoMessage() {}

func (x *PutChartResp) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutChartResp.ProtoReflect.Descriptor instead.
func (*PutChartResp) Descriptor() ([]byte, []int) {
	return file_starmap_proto_rawDescGZIP(), []int{8}
}

func (x *PutChartResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PutChartResp) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *PutChartResp) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *PutChartResp) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *PutChartResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PutChartResp) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PutChartResp) GetMaintainer() string {
	if x != nil {
		return x.Maintainer
	}
	return ""
}

var File_starmap_proto protoreflect.FileDescriptor

const file_starmap_proto_rawDesc = "" +
	"\n" +
	"\rstarmap.proto\x12\x05proto\x1a\x13starmap_model.proto\"\xcb\x01\n" +
	"\x13GetMissingLayersReq\x12\x1e\n" +
	"\n" +
	"apiVersion\x18\x01 \x01(\tR\n" +
	"apiVersion\x12$\n" +
	"\rschemaVersion\x18\x02 \x01(\tR\rschemaVersion\x12\x18\n" +
	"\achartId\x18\x03 \x01(\tR\achartId\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"maintainer\x18\x05 \x01(\tR\n" +
	"maintainer\x12\x16\n" +
	"\x06layers\x18\x06 \x03(\tR\x06layers\"\xca\x06\n" +
	"\x14GetMissingLayersResp\x12\x18\n" +
	"\achartId\x18\x01 \x01(\tR\achartId\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"maintainer\x18\x03 \x01(\tR\n" +
	"maintainer\x12\x1e\n" +
	"\n" +
	"apiVersion\x18\x04 \x01(\tR\n" +
	"apiVersion\x12$\n" +
	"\rschemaVersion\x18\x05 \x01(\tR\rschemaVersion\x12N\n" +
	"\vdataSources\x18\x06 \x03(\v2,.proto.GetMissingLayersResp.DataSourcesEntryR\vdataSources\x12]\n" +
	"\x10storedProcedures\x18\a \x03(\v21.proto.GetMissingLayersResp.StoredProceduresEntryR\x10storedProcedures\x12T\n" +
	"\reventTriggers\x18\b \x03(\v2..proto.GetMissingLayersResp.EventTriggersEntryR\reventTriggers\x12?\n" +
	"\x06events\x18\t \x03(\v2'.proto.GetMissingLayersResp.EventsEntryR\x06events\x1aQ\n" +
	"\x10DataSourcesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.proto.DataSourceR\x05value:\x028\x01\x1a[\n" +
	"\x15StoredProceduresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.proto.StoredProcedureR\x05value:\x028\x01\x1aU\n" +
	"\x12EventTriggersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.proto.EventTriggerR\x05value:\x028\x01\x1aG\n" +
	"\vEventsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\"\n" +
	"\x05value\x18\x02 \x01(\v2\f.proto.EventR\x05value:\x028\x01\"\xad\x01\n" +
	"\rGetChartIdReq\x12\x1e\n" +
	"\n" +
	"apiVersion\x18\x01 \x01(\tR\n" +
	"apiVersion\x12$\n" +
	"\rschemaVersion\x18\x02 \x01(\tR\rschemaVersion\x12\x18\n" +
	"\achartId\x18\x03 \x01(\tR\achartId\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"maintainer\x18\x05 \x01(\tR\n" +
	"maintainer\"\xcc\x01\n" +
	"\x0eDeleteChartReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"maintainer\x18\x04 \x01(\tR\n" +
	"maintainer\x12\x1e\n" +
	"\n" +
	"apiVersion\x18\x05 \x01(\tR\n" +
	"apiVersion\x12$\n" +
	"\rschemaVersion\x18\x06 \x01(\tR\rschemaVersion\x12\x12\n" +
	"\x04kind\x18\a \x01(\tR\x04kind\"\x92\x02\n" +
	"\x12GetChartsLabelsReq\x12\x1e\n" +
	"\n" +
	"apiVersion\x18\x01 \x01(\tR\n" +
	"apiVersion\x12$\n" +
	"\rschemaVersion\x18\x02 \x01(\tR\rschemaVersion\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"maintainer\x18\x04 \x01(\tR\n" +
	"maintainer\x12=\n" +
	"\x06labels\x18\x05 \x03(\v2%.proto.GetChartsLabelsReq.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"B\n" +
	"\x13GetChartsLabelsResp\x12+\n" +
	"\x06charts\x18\x01 \x03(\v2\x13.proto.GetChartRespR\x06charts\"\xb1\x01\n" +
	"\x17GetChartFromMetadataReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"maintainer\x18\x03 \x01(\tR\n" +
	"maintainer\x12\x1e\n" +
	"\n" +
	"apiVersion\x18\x04 \x01(\tR\n" +
	"apiVersion\x12$\n" +
	"\rschemaVersion\x18\x05 \x01(\tR\rschemaVersion\"\xaa\x01\n" +
	"\fGetChartResp\x12\x1e\n" +
	"\n" +
	"apiVersion\x18\x01 \x01(\tR\n" +
	"apiVersion\x12$\n" +
	"\rschemaVersion\x18\x02 \x01(\tR\rschemaVersion\x120\n" +
	"\bmetadata\x18\x03 \x01(\v2\x14.proto.MetadataChartR\bmetadata\x12\"\n" +
	"\x05chart\x18\x04 \x01(\v2\f.proto.ChartR\x05chart\"\xca\x01\n" +
	"\fPutChartResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1e\n" +
	"\n" +
	"apiVersion\x18\x02 \x01(\tR\n" +
	"apiVersion\x12$\n" +
	"\rschemaVersion\x18\x03 \x01(\tR\rschemaVersion\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x06 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"maintainer\x18\a \x01(\tR\n" +
	"maintainer2\xdc\x03\n" +
	"\x0fRegistryService\x123\n" +
	"\bPutChart\x12\x10.proto.StarChart\x1a\x13.proto.PutChartResp\"\x00\x12I\n" +
	"\x10GetChartMetadata\x12\x1e.proto.GetChartFromMetadataReq\x1a\x13.proto.GetChartResp\"\x00\x12J\n" +
	"\x0fGetChartsLabels\x12\x19.proto.GetChartsLabelsReq\x1a\x1a.proto.GetChartsLabelsResp\"\x00\x129\n" +
	"\n" +
	"GetChartId\x12\x14.proto.GetChartIdReq\x1a\x13.proto.GetChartResp\"\x00\x12M\n" +
	"\x10GetMissingLayers\x12\x1a.proto.GetMissingLayersReq\x1a\x1b.proto.GetMissingLayersResp\"\x00\x12;\n" +
	"\vDeleteChart\x12\x15.proto.DeleteChartReq\x1a\x13.proto.EmptyMessage\"\x00\x126\n" +
	"\vUpdateChart\x12\x10.proto.StarChart\x1a\x13.proto.PutChartResp\"\x00B\x1dZ\x1bgithub.com/c12s/starmap/apib\x06proto3"

var (
	file_starmap_proto_rawDescOnce sync.Once
	file_starmap_proto_rawDescData []byte
)

func file_starmap_proto_rawDescGZIP() []byte {
	file_starmap_proto_rawDescOnce.Do(func() {
		file_starmap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_starmap_proto_rawDesc), len(file_starmap_proto_rawDesc)))
	})
	return file_starmap_proto_rawDescData
}

var file_starmap_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_starmap_proto_goTypes = []any{
	(*GetMissingLayersReq)(nil),     // 0: proto.GetMissingLayersReq
	(*GetMissingLayersResp)(nil),    // 1: proto.GetMissingLayersResp
	(*GetChartIdReq)(nil),           // 2: proto.GetChartIdReq
	(*DeleteChartReq)(nil),          // 3: proto.DeleteChartReq
	(*GetChartsLabelsReq)(nil),      // 4: proto.GetChartsLabelsReq
	(*GetChartsLabelsResp)(nil),     // 5: proto.GetChartsLabelsResp
	(*GetChartFromMetadataReq)(nil), // 6: proto.GetChartFromMetadataReq
	(*GetChartResp)(nil),            // 7: proto.GetChartResp
	(*PutChartResp)(nil),            // 8: proto.PutChartResp
	nil,                             // 9: proto.GetMissingLayersResp.DataSourcesEntry
	nil,                             // 10: proto.GetMissingLayersResp.StoredProceduresEntry
	nil,                             // 11: proto.GetMissingLayersResp.EventTriggersEntry
	nil,                             // 12: proto.GetMissingLayersResp.EventsEntry
	nil,                             // 13: proto.GetChartsLabelsReq.LabelsEntry
	(*MetadataChart)(nil),           // 14: proto.MetadataChart
	(*Chart)(nil),                   // 15: proto.Chart
	(*DataSource)(nil),              // 16: proto.DataSource
	(*StoredProcedure)(nil),         // 17: proto.StoredProcedure
	(*EventTrigger)(nil),            // 18: proto.EventTrigger
	(*Event)(nil),                   // 19: proto.Event
	(*StarChart)(nil),               // 20: proto.StarChart
	(*EmptyMessage)(nil),            // 21: proto.EmptyMessage
}
var file_starmap_proto_depIdxs = []int32{
	9,  // 0: proto.GetMissingLayersResp.dataSources:type_name -> proto.GetMissingLayersResp.DataSourcesEntry
	10, // 1: proto.GetMissingLayersResp.storedProcedures:type_name -> proto.GetMissingLayersResp.StoredProceduresEntry
	11, // 2: proto.GetMissingLayersResp.eventTriggers:type_name -> proto.GetMissingLayersResp.EventTriggersEntry
	12, // 3: proto.GetMissingLayersResp.events:type_name -> proto.GetMissingLayersResp.EventsEntry
	13, // 4: proto.GetChartsLabelsReq.labels:type_name -> proto.GetChartsLabelsReq.LabelsEntry
	7,  // 5: proto.GetChartsLabelsResp.charts:type_name -> proto.GetChartResp
	14, // 6: proto.GetChartResp.metadata:type_name -> proto.MetadataChart
	15, // 7: proto.GetChartResp.chart:type_name -> proto.Chart
	16, // 8: proto.GetMissingLayersResp.DataSourcesEntry.value:type_name -> proto.DataSource
	17, // 9: proto.GetMissingLayersResp.StoredProceduresEntry.value:type_name -> proto.StoredProcedure
	18, // 10: proto.GetMissingLayersResp.EventTriggersEntry.value:type_name -> proto.EventTrigger
	19, // 11: proto.GetMissingLayersResp.EventsEntry.value:type_name -> proto.Event
	20, // 12: proto.RegistryService.PutChart:input_type -> proto.StarChart
	6,  // 13: proto.RegistryService.GetChartMetadata:input_type -> proto.GetChartFromMetadataReq
	4,  // 14: proto.RegistryService.GetChartsLabels:input_type -> proto.GetChartsLabelsReq
	2,  // 15: proto.RegistryService.GetChartId:input_type -> proto.GetChartIdReq
	0,  // 16: proto.RegistryService.GetMissingLayers:input_type -> proto.GetMissingLayersReq
	3,  // 17: proto.RegistryService.DeleteChart:input_type -> proto.DeleteChartReq
	20, // 18: proto.RegistryService.UpdateChart:input_type -> proto.StarChart
	8,  // 19: proto.RegistryService.PutChart:output_type -> proto.PutChartResp
	7,  // 20: proto.RegistryService.GetChartMetadata:output_type -> proto.GetChartResp
	5,  // 21: proto.RegistryService.GetChartsLabels:output_type -> proto.GetChartsLabelsResp
	7,  // 22: proto.RegistryService.GetChartId:output_type -> proto.GetChartResp
	1,  // 23: proto.RegistryService.GetMissingLayers:output_type -> proto.GetMissingLayersResp
	21, // 24: proto.RegistryService.DeleteChart:output_type -> proto.EmptyMessage
	8,  // 25: proto.RegistryService.UpdateChart:output_type -> proto.PutChartResp
	19, // [19:26] is the sub-list for method output_type
	12, // [12:19] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_starmap_proto_init() }
func file_starmap_proto_init() {
	if File_starmap_proto != nil {
		return
	}
	file_starmap_model_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_starmap_proto_rawDesc), len(file_starmap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_starmap_proto_goTypes,
		DependencyIndexes: file_starmap_proto_depIdxs,
		MessageInfos:      file_starmap_proto_msgTypes,
	}.Build()
	File_starmap_proto = out.File
	file_starmap_proto_goTypes = nil
	file_starmap_proto_depIdxs = nil
}
