// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: starmap.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PushLayer: CI/CD javlja novu verziju layera.
// Layer se identifikuje po image (oci) ILI pull+command (git) — isto kao hash u modelu.
type PushLayerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceType    string                 `protobuf:"bytes,1,opt,name=sourceType,proto3" json:"sourceType,omitempty"` // "oci" | "git"
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`           // oci: image BEZ taga (ghcr.io/ana/api)
	Pull          string                 `protobuf:"bytes,3,opt,name=pull,proto3" json:"pull,omitempty"`             // git: repo URL
	Command       string                 `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`       // git: build komanda
	Sha           string                 `protobuf:"bytes,5,opt,name=sha,proto3" json:"sha,omitempty"`               // OBAVEZNO: OCI digest ili git commit — tacno sta povuci
	Semver        string                 `protobuf:"bytes,6,opt,name=semver,proto3" json:"semver,omitempty"`         // opciono: ako prazno -> auto-increment
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushLayerReq) Reset() {
	*x = PushLayerReq{}
	mi := &file_starmap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushLayerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushLayerReq) ProtoMessage() {}

func (x *PushLayerReq) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushLayerReq.ProtoReflect.Descriptor instead.
func (*PushLayerReq) Descriptor() ([]byte, []int) {
	return file_starmap_proto_rawDescGZIP(), []int{0}
}

func (x *PushLayerReq) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *PushLayerReq) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *PushLayerReq) GetPull() string {
	if x != nil {
		return x.Pull
	}
	return ""
}

func (x *PushLayerReq) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *PushLayerReq) GetSha() string {
	if x != nil {
		return x.Sha
	}
	return ""
}

func (x *PushLayerReq) GetSemver() string {
	if x != nil {
		return x.Semver
	}
	return ""
}

type PushLayerResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Sha            string                 `protobuf:"bytes,1,opt,name=sha,proto3" json:"sha,omitempty"`
	Semver         string                 `protobuf:"bytes,2,opt,name=semver,proto3" json:"semver,omitempty"`
	PreviousSemver string                 `protobuf:"bytes,3,opt,name=previousSemver,proto3" json:"previousSemver,omitempty"` // prazno ako je prva verzija
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PushLayerResp) Reset() {
	*x = PushLayerResp{}
	mi := &file_starmap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushLayerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushLayerResp) ProtoMessage() {}

func (x *PushLayerResp) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushLayerResp.ProtoReflect.Descriptor instead.
func (*PushLayerResp) Descriptor() ([]byte, []int) {
	return file_starmap_proto_rawDescGZIP(), []int{1}
}

func (x *PushLayerResp) GetSha() string {
	if x != nil {
		return x.Sha
	}
	return ""
}

func (x *PushLayerResp) GetSemver() string {
	if x != nil {
		return x.Semver
	}
	return ""
}

func (x *PushLayerResp) GetPreviousSemver() string {
	if x != nil {
		return x.PreviousSemver
	}
	return ""
}

type ListLayerVersionsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Pull          string                 `protobuf:"bytes,2,opt,name=pull,proto3" json:"pull,omitempty"`
	Command       string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLayerVersionsReq) Reset() {
	*x = ListLayerVersionsReq{}
	mi := &file_starmap_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLayerVersionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLayerVersionsReq) ProtoMessage() {}

func (x *ListLayerVersionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLayerVersionsReq.ProtoReflect.Descriptor instead.
func (*ListLayerVersionsReq) Descriptor() ([]byte, []int) {
	return file_starmap_proto_rawDescGZIP(), []int{2}
}

func (x *ListLayerVersionsReq) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ListLayerVersionsReq) GetPull() string {
	if x != nil {
		return x.Pull
	}
	return ""
}

func (x *ListLayerVersionsReq) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type LayerVersionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sha           string                 `protobuf:"bytes,1,opt,name=sha,proto3" json:"sha,omitempty"`
	Semver        string                 `protobuf:"bytes,2,opt,name=semver,proto3" json:"semver,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	IsLatest      bool                   `protobuf:"varint,4,opt,name=isLatest,proto3" json:"isLatest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LayerVersionInfo) Reset() {
	*x = LayerVersionInfo{}
	mi := &file_starmap_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LayerVersionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LayerVersionInfo) ProtoMessage() {}

func (x *LayerVersionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LayerVersionInfo.ProtoReflect.Descriptor instead.
func (*LayerVersionInfo) Descriptor() ([]byte, []int) {
	return file_starmap_proto_rawDescGZIP(), []int{3}
}

func (x *LayerVersionInfo) GetSha() string {
	if x != nil {
		return x.Sha
	}
	return ""
}

func (x *LayerVersionInfo) GetSemver() string {
	if x != nil {
		return x.Semver
	}
	return ""
}

func (x *LayerVersionInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *LayerVersionInfo) GetIsLatest() bool {
	if x != nil {
		return x.IsLatest
	}
	return false
}

type ListLayerVersionsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceType    string                 `protobuf:"bytes,1,opt,name=sourceType,proto3" json:"sourceType,omitempty"`
	Versions      []*LayerVersionInfo    `protobuf:"bytes,2,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLayerVersionsResp) Reset() {
	*x = ListLayerVersionsResp{}
	mi := &file_starmap_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLayerVersionsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLayerVersionsResp) ProtoMessage() {}

func (x *ListLayerVersionsResp) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLayerVersionsResp.ProtoReflect.Descriptor instead.
func (*ListLayerVersionsResp) Descriptor() ([]byte, []int) {
	return file_starmap_proto_rawDescGZIP(), []int{4}
}

func (x *ListLayerVersionsResp) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *ListLayerVersionsResp) GetVersions() []*LayerVersionInfo {
	if x != nil {
		return x.Versions
	}
	return nil
}

type SearchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DeepSearch    bool                   `protobuf:"varint,4,opt,name=deepSearch,proto3" json:"deepSearch,omitempty"`
	ComponentTags map[string]string      `protobuf:"bytes,5,rep,name=componentTags,proto3" json:"componentTags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchReq) Reset() {
	*x = SearchReq{}
	mi := &file_starmap_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchReq) ProtoMessage() {}

func (x *SearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchReq.ProtoReflect.Descriptor instead.
func (*SearchReq) Descriptor() ([]byte, []int) {
	return file_starmap_proto_rawDescGZIP(), []int{5}
}

func (x *SearchReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SearchReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SearchReq) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SearchReq) GetDeepSearch() bool {
	if x != nil {
		return x.DeepSearch
	}
	return false
}

func (x *SearchReq) GetComponentTags() map[string]string {
	if x != nil {
		return x.ComponentTags
	}
	return nil
}

type ExtendReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldVersion    string                 `protobuf:"bytes,1,opt,name=oldVersion,proto3" json:"oldVersion,omitempty"`
	Chart         *StarChart             `protobuf:"bytes,2,opt,name=chart,proto3" json:"chart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtendReq) Reset() {
	*x = ExtendReq{}
	mi := &file_starmap_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendReq) ProtoMessage() {}

func (x *ExtendReq) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendReq.ProtoReflect.Descriptor instead.
func (*ExtendReq) Descriptor() ([]byte, []int) {
	return file_starmap_proto_rawDescGZIP(), []int{6}
}

func (x *ExtendReq) GetOldVersion() string {
	if x != nil {
		return x.OldVersion
	}
	return ""
}

func (x *ExtendReq) GetChart() *StarChart {
	if x != nil {
		return x.Chart
	}
	return nil
}

type TimelineReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChartId       string                 `protobuf:"bytes,1,opt,name=chartId,proto3" json:"chartId,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Maintainer    string                 `protobuf:"bytes,3,opt,name=maintainer,proto3" json:"maintainer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimelineReq) Reset() {
	*x = TimelineReq{}
	mi := &file_starmap_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimelineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimelineReq) ProtoMessage() {}

func (x *TimelineReq) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimelineReq.ProtoReflect.Descriptor instead.
func (*TimelineReq) Descriptor() ([]byte, []int) {
	return file_starmap_proto_rawDescGZIP(), []int{7}
}

func (x *TimelineReq) GetChartId() string {
	if x != nil {
		return x.ChartId
	}
	return ""
}

func (x *TimelineReq) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *TimelineReq) GetMaintainer() string {
	if x != nil {
		return x.Maintainer
	}
	return ""
}

type TimelineResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Charts        []*GetChartResp        `protobuf:"bytes,1,rep,name=charts,proto3" json:"charts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimelineResp) Reset() {
	*x = TimelineResp{}
	mi := &file_starmap_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimelineResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimelineResp) ProtoMessage() {}

func (x *TimelineResp) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimelineResp.ProtoReflect.Descriptor instead.
func (*TimelineResp) Descriptor() ([]byte, []int) {
	return file_starmap_proto_rawDescGZIP(), []int{8}
}

func (x *TimelineResp) GetCharts() []*GetChartResp {
	if x != nil {
		return x.Charts
	}
	return nil
}

type SwitchCheckpointResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *LayersResp            `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	Stop          *LayersResp            `protobuf:"bytes,2,opt,name=stop,proto3" json:"stop,omitempty"`
	Download      *LayersResp            `protobuf:"bytes,3,opt,name=download,proto3" json:"download,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchCheckpointResp) Reset() {
	*x = SwitchCheckpointResp{}
	mi := &file_starmap_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchCheckpointResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchCheckpointResp) ProtoMessage() {}

func (x *SwitchCheckpointResp) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchCheckpointResp.ProtoReflect.Descriptor instead.
func (*SwitchCheckpointResp) Descriptor() ([]byte, []int) {
	return file_starmap_proto_rawDescGZIP(), []int{9}
}

func (x *SwitchCheckpointResp) GetStart() *LayersResp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *SwitchCheckpointResp) GetStop() *LayersResp {
	if x != nil {
		return x.Stop
	}
	return nil
}

func (x *SwitchCheckpointResp) GetDownload() *LayersResp {
	if x != nil {
		return x.Download
	}
	return nil
}

type SwitchCheckpointReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChartId       string                 `protobuf:"bytes,1,opt,name=chartId,proto3" json:"chartId,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Maintainer    string                 `protobuf:"bytes,3,opt,name=maintainer,proto3" json:"maintainer,omitempty"`
	OldVersion    string                 `protobuf:"bytes,4,opt,name=oldVersion,proto3" json:"oldVersion,omitempty"`
	NewVersion    string                 `protobuf:"bytes,5,opt,name=newVersion,proto3" json:"newVersion,omitempty"`
	Layers        []string               `protobuf:"bytes,6,rep,name=layers,proto3" json:"layers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchCheckpointReq) Reset() {
	*x = SwitchCheckpointReq{}
	mi := &file_starmap_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchCheckpointReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchCheckpointReq) ProtoMessage() {}

func (x *SwitchCheckpointReq) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchCheckpointReq.ProtoReflect.Descriptor instead.
func (*SwitchCheckpointReq) Descriptor() ([]byte, []int) {
	return file_starmap_proto_rawDescGZIP(), []int{10}
}

func (x *SwitchCheckpointReq) GetChartId() string {
	if x != nil {
		return x.ChartId
	}
	return ""
}

func (x *SwitchCheckpointReq) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SwitchCheckpointReq) GetMaintainer() string {
	if x != nil {
		return x.Maintainer
	}
	return ""
}

func (x *SwitchCheckpointReq) GetOldVersion() string {
	if x != nil {
		return x.OldVersion
	}
	return ""
}

func (x *SwitchCheckpointReq) GetNewVersion() string {
	if x != nil {
		return x.NewVersion
	}
	return ""
}

func (x *SwitchCheckpointReq) GetLayers() []string {
	if x != nil {
		return x.Layers
	}
	return nil
}

type LayersResp struct {
	state            protoimpl.MessageState      `protogen:"open.v1"`
	DataSources      map[string]*DataSource      `protobuf:"bytes,1,rep,name=dataSources,proto3" json:"dataSources,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StoredProcedures map[string]*StoredProcedure `protobuf:"bytes,2,rep,name=storedProcedures,proto3" json:"storedProcedures,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	EventTriggers    map[string]*EventTrigger    `protobuf:"bytes,3,rep,name=eventTriggers,proto3" json:"eventTriggers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Events           map[string]*Event           `protobuf:"bytes,4,rep,name=events,proto3" json:"events,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Entrypoints      map[string]*Entrypoint      `protobuf:"bytes,5,rep,name=entrypoints,proto3" json:"entrypoints,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LayersResp) Reset() {
	*x = LayersResp{}
	mi := &file_starmap_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LayersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LayersResp) ProtoMessage() {}

func (x *LayersResp) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LayersResp.ProtoReflect.Descriptor instead.
func (*LayersResp) Descriptor() ([]byte, []int) {
	return file_starmap_proto_rawDescGZIP(), []int{11}
}

func (x *LayersResp) GetDataSources() map[string]*DataSource {
	if x != nil {
		return x.DataSources
	}
	return nil
}

func (x *LayersResp) GetStoredProcedures() map[string]*StoredProcedure {
	if x != nil {
		return x.StoredProcedures
	}
	return nil
}

func (x *LayersResp) GetEventTriggers() map[string]*EventTrigger {
	if x != nil {
		return x.EventTriggers
	}
	return nil
}

func (x *LayersResp) GetEvents() map[string]*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *LayersResp) GetEntrypoints() map[string]*Entrypoint {
	if x != nil {
		return x.Entrypoints
	}
	return nil
}

type GetMissingLayersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion string                 `protobuf:"bytes,1,opt,name=schemaVersion,proto3" json:"schemaVersion,omitempty"`
	ChartId       string                 `protobuf:"bytes,2,opt,name=chartId,proto3" json:"chartId,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Maintainer    string                 `protobuf:"bytes,4,opt,name=maintainer,proto3" json:"maintainer,omitempty"`
	Layers        []string               `protobuf:"bytes,5,rep,name=layers,proto3" json:"layers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMissingLayersReq) Reset() {
	*x = GetMissingLayersReq{}
	mi := &file_starmap_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMissingLayersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMissingLayersReq) ProtoMessage() {}

func (x *GetMissingLayersReq) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMissingLayersReq.ProtoReflect.Descriptor instead.
func (*GetMissingLayersReq) Descriptor() ([]byte, []int) {
	return file_starmap_proto_rawDescGZIP(), []int{12}
}

func (x *GetMissingLayersReq) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *GetMissingLayersReq) GetChartId() string {
	if x != nil {
		return x.ChartId
	}
	return ""
}

func (x *GetMissingLayersReq) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetMissingLayersReq) GetMaintainer() string {
	if x != nil {
		return x.Maintainer
	}
	return ""
}

func (x *GetMissingLayersReq) GetLayers() []string {
	if x != nil {
		return x.Layers
	}
	return nil
}

type GetMissingLayersResp struct {
	state            protoimpl.MessageState      `protogen:"open.v1"`
	ChartId          string                      `protobuf:"bytes,1,opt,name=chartId,proto3" json:"chartId,omitempty"`
	Namespace        string                      `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Maintainer       string                      `protobuf:"bytes,3,opt,name=maintainer,proto3" json:"maintainer,omitempty"`
	ApiVersion       string                      `protobuf:"bytes,4,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	SchemaVersion    string                      `protobuf:"bytes,5,opt,name=schemaVersion,proto3" json:"schemaVersion,omitempty"`
	DataSources      map[string]*DataSource      `protobuf:"bytes,6,rep,name=dataSources,proto3" json:"dataSources,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StoredProcedures map[string]*StoredProcedure `protobuf:"bytes,7,rep,name=storedProcedures,proto3" json:"storedProcedures,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	EventTriggers    map[string]*EventTrigger    `protobuf:"bytes,8,rep,name=eventTriggers,proto3" json:"eventTriggers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Events           map[string]*Event           `protobuf:"bytes,9,rep,name=events,proto3" json:"events,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Entrypoints      map[string]*Entrypoint      `protobuf:"bytes,10,rep,name=entrypoints,proto3" json:"entrypoints,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetMissingLayersResp) Reset() {
	*x = GetMissingLayersResp{}
	mi := &file_starmap_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMissingLayersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMissingLayersResp) ProtoMessage() {}

func (x *GetMissingLayersResp) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMissingLayersResp.ProtoReflect.Descriptor instead.
func (*GetMissingLayersResp) Descriptor() ([]byte, []int) {
	return file_starmap_proto_rawDescGZIP(), []int{13}
}

func (x *GetMissingLayersResp) GetChartId() string {
	if x != nil {
		return x.ChartId
	}
	return ""
}

func (x *GetMissingLayersResp) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetMissingLayersResp) GetMaintainer() string {
	if x != nil {
		return x.Maintainer
	}
	return ""
}

func (x *GetMissingLayersResp) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *GetMissingLayersResp) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *GetMissingLayersResp) GetDataSources() map[string]*DataSource {
	if x != nil {
		return x.DataSources
	}
	return nil
}

func (x *GetMissingLayersResp) GetStoredProcedures() map[string]*StoredProcedure {
	if x != nil {
		return x.StoredProcedures
	}
	return nil
}

func (x *GetMissingLayersResp) GetEventTriggers() map[string]*EventTrigger {
	if x != nil {
		return x.EventTriggers
	}
	return nil
}

func (x *GetMissingLayersResp) GetEvents() map[string]*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *GetMissingLayersResp) GetEntrypoints() map[string]*Entrypoint {
	if x != nil {
		return x.Entrypoints
	}
	return nil
}

type GetChartIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion string                 `protobuf:"bytes,1,opt,name=schemaVersion,proto3" json:"schemaVersion,omitempty"`
	ChartId       string                 `protobuf:"bytes,2,opt,name=chartId,proto3" json:"chartId,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Maintainer    string                 `protobuf:"bytes,4,opt,name=maintainer,proto3" json:"maintainer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChartIdReq) Reset() {
	*x = GetChartIdReq{}
	mi := &file_starmap_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChartIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChartIdReq) ProtoMessage() {}

func (x *GetChartIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChartIdReq.ProtoReflect.Descriptor instead.
func (*GetChartIdReq) Descriptor() ([]byte, []int) {
	return file_starmap_proto_rawDescGZIP(), []int{14}
}

func (x *GetChartIdReq) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *GetChartIdReq) GetChartId() string {
	if x != nil {
		return x.ChartId
	}
	return ""
}

func (x *GetChartIdReq) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetChartIdReq) GetMaintainer() string {
	if x != nil {
		return x.Maintainer
	}
	return ""
}

type DeleteChartReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Maintainer    string                 `protobuf:"bytes,4,opt,name=maintainer,proto3" json:"maintainer,omitempty"`
	SchemaVersion string                 `protobuf:"bytes,5,opt,name=schemaVersion,proto3" json:"schemaVersion,omitempty"`
	Kind          string                 `protobuf:"bytes,6,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChartReq) Reset() {
	*x = DeleteChartReq{}
	mi := &file_starmap_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChartReq) ProtoMessage() {}

func (x *DeleteChartReq) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChartReq.ProtoReflect.Descriptor instead.
func (*DeleteChartReq) Descriptor() ([]byte, []int) {
	return file_starmap_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteChartReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteChartReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteChartReq) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DeleteChartReq) GetMaintainer() string {
	if x != nil {
		return x.Maintainer
	}
	return ""
}

func (x *DeleteChartReq) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *DeleteChartReq) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type GetChartsLabelsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion string                 `protobuf:"bytes,1,opt,name=schemaVersion,proto3" json:"schemaVersion,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Maintainer    string                 `protobuf:"bytes,3,opt,name=maintainer,proto3" json:"maintainer,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChartsLabelsReq) Reset() {
	*x = GetChartsLabelsReq{}
	mi := &file_starmap_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChartsLabelsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChartsLabelsReq) ProtoMessage() {}

func (x *GetChartsLabelsReq) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChartsLabelsReq.ProtoReflect.Descriptor instead.
func (*GetChartsLabelsReq) Descriptor() ([]byte, []int) {
	return file_starmap_proto_rawDescGZIP(), []int{16}
}

func (x *GetChartsLabelsReq) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *GetChartsLabelsReq) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetChartsLabelsReq) GetMaintainer() string {
	if x != nil {
		return x.Maintainer
	}
	return ""
}

func (x *GetChartsLabelsReq) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type GetChartsLabelsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Charts        []*GetChartResp        `protobuf:"bytes,1,rep,name=charts,proto3" json:"charts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChartsLabelsResp) Reset() {
	*x = GetChartsLabelsResp{}
	mi := &file_starmap_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChartsLabelsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChartsLabelsResp) ProtoMessage() {}

func (x *GetChartsLabelsResp) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChartsLabelsResp.ProtoReflect.Descriptor instead.
func (*GetChartsLabelsResp) Descriptor() ([]byte, []int) {
	return file_starmap_proto_rawDescGZIP(), []int{17}
}

func (x *GetChartsLabelsResp) GetCharts() []*GetChartResp {
	if x != nil {
		return x.Charts
	}
	return nil
}

type GetChartFromMetadataReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Maintainer    string                 `protobuf:"bytes,3,opt,name=maintainer,proto3" json:"maintainer,omitempty"`
	SchemaVersion string                 `protobuf:"bytes,4,opt,name=schemaVersion,proto3" json:"schemaVersion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChartFromMetadataReq) Reset() {
	*x = GetChartFromMetadataReq{}
	mi := &file_starmap_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChartFromMetadataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChartFromMetadataReq) ProtoMessage() {}

func (x *GetChartFromMetadataReq) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChartFromMetadataReq.ProtoReflect.Descriptor instead.
func (*GetChartFromMetadataReq) Descriptor() ([]byte, []int) {
	return file_starmap_proto_rawDescGZIP(), []int{18}
}

func (x *GetChartFromMetadataReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetChartFromMetadataReq) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetChartFromMetadataReq) GetMaintainer() string {
	if x != nil {
		return x.Maintainer
	}
	return ""
}

func (x *GetChartFromMetadataReq) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

type GetChartResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	SchemaVersion string                 `protobuf:"bytes,2,opt,name=schemaVersion,proto3" json:"schemaVersion,omitempty"`
	Metadata      *MetadataChart         `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Chart         *Chart                 `protobuf:"bytes,4,opt,name=chart,proto3" json:"chart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChartResp) Reset() {
	*x = GetChartResp{}
	mi := &file_starmap_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChartResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChartResp) ProtoMessage() {}

func (x *GetChartResp) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChartResp.ProtoReflect.Descriptor instead.
func (*GetChartResp) Descriptor() ([]byte, []int) {
	return file_starmap_proto_rawDescGZIP(), []int{19}
}

func (x *GetChartResp) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *GetChartResp) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *GetChartResp) GetMetadata() *MetadataChart {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetChartResp) GetChart() *Chart {
	if x != nil {
		return x.Chart
	}
	return nil
}

type PutChartResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ApiVersion    string                 `protobuf:"bytes,2,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	SchemaVersion string                 `protobuf:"bytes,3,opt,name=schemaVersion,proto3" json:"schemaVersion,omitempty"`
	Kind          string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,6,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Maintainer    string                 `protobuf:"bytes,7,opt,name=maintainer,proto3" json:"maintainer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutChartResp) Reset() {
	*x = PutChartResp{}
	mi := &file_starmap_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutChartResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutChartResp) ProtoMessage() {}

func (x *PutChartResp) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutChartResp.ProtoReflect.Descriptor instead.
func (*PutChartResp) Descriptor() ([]byte, []int) {
	return file_starmap_proto_rawDescGZIP(), []int{20}
}

func (x *PutChartResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PutChartResp) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *PutChartResp) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *PutChartResp) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *PutChartResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PutChartResp) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PutChartResp) GetMaintainer() string {
	if x != nil {
		return x.Maintainer
	}
	return ""
}

var File_starmap_proto protoreflect.FileDescriptor

const file_starmap_proto_rawDesc = "" +
	"\n" +
	"\rstarmap.proto\x12\x05proto\x1a\x13starmap_model.proto\"\x9c\x01\n" +
	"\fPushLayerReq\x12\x1e\n" +
	"\n" +
	"sourceType\x18\x01 \x01(\tR\n" +
	"sourceType\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x12\n" +
	"\x04pull\x18\x03 \x01(\tR\x04pull\x12\x18\n" +
	"\acommand\x18\x04 \x01(\tR\acommand\x12\x10\n" +
	"\x03sha\x18\x05 \x01(\tR\x03sha\x12\x16\n" +
	"\x06semver\x18\x06 \x01(\tR\x06semver\"a\n" +
	"\rPushLayerResp\x12\x10\n" +
	"\x03sha\x18\x01 \x01(\tR\x03sha\x12\x16\n" +
	"\x06semver\x18\x02 \x01(\tR\x06semver\x12&\n" +
	"\x0epreviousSemver\x18\x03 \x01(\tR\x0epreviousSemver\"Z\n" +
	"\x14ListLayerVersionsReq\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12\x12\n" +
	"\x04pull\x18\x02 \x01(\tR\x04pull\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\"v\n" +
	"\x10LayerVersionInfo\x12\x10\n" +
	"\x03sha\x18\x01 \x01(\tR\x03sha\x12\x16\n" +
	"\x06semver\x18\x02 \x01(\tR\x06semver\x12\x1c\n" +
	"\tcreatedAt\x18\x03 \x01(\x03R\tcreatedAt\x12\x1a\n" +
	"\bisLatest\x18\x04 \x01(\bR\bisLatest\"l\n" +
	"\x15ListLayerVersionsResp\x12\x1e\n" +
	"\n" +
	"sourceType\x18\x01 \x01(\tR\n" +
	"sourceType\x123\n" +
	"\bversions\x18\x02 \x03(\v2\x17.proto.LayerVersionInfoR\bversions\"\xd7\x02\n" +
	"\tSearchReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12.\n" +
	"\x04tags\x18\x03 \x03(\v2\x1a.proto.SearchReq.TagsEntryR\x04tags\x12\x1e\n" +
	"\n" +
	"deepSearch\x18\x04 \x01(\bR\n" +
	"deepSearch\x12I\n" +
	"\rcomponentTags\x18\x05 \x03(\v2#.proto.SearchReq.ComponentTagsEntryR\rcomponentTags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a@\n" +
	"\x12ComponentTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"S\n" +
	"\tExtendReq\x12\x1e\n" +
	"\n" +
	"oldVersion\x18\x01 \x01(\tR\n" +
	"oldVersion\x12&\n" +
	"\x05chart\x18\x02 \x01(\v2\x10.proto.StarChartR\x05chart\"e\n" +
	"\vTimelineReq\x12\x18\n" +
	"\achartId\x18\x01 \x01(\tR\achartId\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"maintainer\x18\x03 \x01(\tR\n" +
	"maintainer\";\n" +
	"\fTimelineResp\x12+\n" +
	"\x06charts\x18\x01 \x03(\v2\x13.proto.GetChartRespR\x06charts\"\x95\x01\n" +
	"\x14SwitchCheckpointResp\x12'\n" +
	"\x05start\x18\x01 \x01(\v2\x11.proto.LayersRespR\x05start\x12%\n" +
	"\x04stop\x18\x02 \x01(\v2\x11.proto.LayersRespR\x04stop\x12-\n" +
	"\bdownload\x18\x03 \x01(\v2\x11.proto.LayersRespR\bdownload\"\xc5\x01\n" +
	"\x13SwitchCheckpointReq\x12\x18\n" +
	"\achartId\x18\x01 \x01(\tR\achartId\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"maintainer\x18\x03 \x01(\tR\n" +
	"maintainer\x12\x1e\n" +
	"\n" +
	"oldVersion\x18\x04 \x01(\tR\n" +
	"oldVersion\x12\x1e\n" +
	"\n" +
	"newVersion\x18\x05 \x01(\tR\n" +
	"newVersion\x12\x16\n" +
	"\x06layers\x18\x06 \x03(\tR\x06layers\"\x93\x06\n" +
	"\n" +
	"LayersResp\x12D\n" +
	"\vdataSources\x18\x01 \x03(\v2\".proto.LayersResp.DataSourcesEntryR\vdataSources\x12S\n" +
	"\x10storedProcedures\x18\x02 \x03(\v2'.proto.LayersResp.StoredProceduresEntryR\x10storedProcedures\x12J\n" +
	"\reventTriggers\x18\x03 \x03(\v2$.proto.LayersResp.EventTriggersEntryR\reventTriggers\x125\n" +
	"\x06events\x18\x04 \x03(\v2\x1d.proto.LayersResp.EventsEntryR\x06events\x12D\n" +
	"\ventrypoints\x18\x05 \x03(\v2\".proto.LayersResp.EntrypointsEntryR\ventrypoints\x1aQ\n" +
	"\x10DataSourcesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.proto.DataSourceR\x05value:\x028\x01\x1a[\n" +
	"\x15StoredProceduresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.proto.StoredProcedureR\x05value:\x028\x01\x1aU\n" +
	"\x12EventTriggersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.proto.EventTriggerR\x05value:\x028\x01\x1aG\n" +
	"\vEventsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\"\n" +
	"\x05value\x18\x02 \x01(\v2\f.proto.EventR\x05value:\x028\x01\x1aQ\n" +
	"\x10EntrypointsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.proto.EntrypointR\x05value:\x028\x01\"\xab\x01\n" +
	"\x13GetMissingLayersReq\x12$\n" +
	"\rschemaVersion\x18\x01 \x01(\tR\rschemaVersion\x12\x18\n" +
	"\achartId\x18\x02 \x01(\tR\achartId\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"maintainer\x18\x04 \x01(\tR\n" +
	"maintainer\x12\x16\n" +
	"\x06layers\x18\x05 \x03(\tR\x06layers\"\xed\a\n" +
	"\x14GetMissingLayersResp\x12\x18\n" +
	"\achartId\x18\x01 \x01(\tR\achartId\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"maintainer\x18\x03 \x01(\tR\n" +
	"maintainer\x12\x1e\n" +
	"\n" +
	"apiVersion\x18\x04 \x01(\tR\n" +
	"apiVersion\x12$\n" +
	"\rschemaVersion\x18\x05 \x01(\tR\rschemaVersion\x12N\n" +
	"\vdataSources\x18\x06 \x03(\v2,.proto.GetMissingLayersResp.DataSourcesEntryR\vdataSources\x12]\n" +
	"\x10storedProcedures\x18\a \x03(\v21.proto.GetMissingLayersResp.StoredProceduresEntryR\x10storedProcedures\x12T\n" +
	"\reventTriggers\x18\b \x03(\v2..proto.GetMissingLayersResp.EventTriggersEntryR\reventTriggers\x12?\n" +
	"\x06events\x18\t \x03(\v2'.proto.GetMissingLayersResp.EventsEntryR\x06events\x12N\n" +
	"\ventrypoints\x18\n" +
	" \x03(\v2,.proto.GetMissingLayersResp.EntrypointsEntryR\ventrypoints\x1aQ\n" +
	"\x10DataSourcesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.proto.DataSourceR\x05value:\x028\x01\x1a[\n" +
	"\x15StoredProceduresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.proto.StoredProcedureR\x05value:\x028\x01\x1aU\n" +
	"\x12EventTriggersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.proto.EventTriggerR\x05value:\x028\x01\x1aG\n" +
	"\vEventsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\"\n" +
	"\x05value\x18\x02 \x01(\v2\f.proto.EventR\x05value:\x028\x01\x1aQ\n" +
	"\x10EntrypointsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.proto.EntrypointR\x05value:\x028\x01\"\x8d\x01\n" +
	"\rGetChartIdReq\x12$\n" +
	"\rschemaVersion\x18\x01 \x01(\tR\rschemaVersion\x12\x18\n" +
	"\achartId\x18\x02 \x01(\tR\achartId\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"maintainer\x18\x04 \x01(\tR\n" +
	"maintainer\"\xac\x01\n" +
	"\x0eDeleteChartReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"maintainer\x18\x04 \x01(\tR\n" +
	"maintainer\x12$\n" +
	"\rschemaVersion\x18\x05 \x01(\tR\rschemaVersion\x12\x12\n" +
	"\x04kind\x18\x06 \x01(\tR\x04kind\"\xf2\x01\n" +
	"\x12GetChartsLabelsReq\x12$\n" +
	"\rschemaVersion\x18\x01 \x01(\tR\rschemaVersion\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"maintainer\x18\x03 \x01(\tR\n" +
	"maintainer\x12=\n" +
	"\x06labels\x18\x04 \x03(\v2%.proto.GetChartsLabelsReq.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"B\n" +
	"\x13GetChartsLabelsResp\x12+\n" +
	"\x06charts\x18\x01 \x03(\v2\x13.proto.GetChartRespR\x06charts\"\x91\x01\n" +
	"\x17GetChartFromMetadataReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"maintainer\x18\x03 \x01(\tR\n" +
	"maintainer\x12$\n" +
	"\rschemaVersion\x18\x04 \x01(\tR\rschemaVersion\"\xaa\x01\n" +
	"\fGetChartResp\x12\x1e\n" +
	"\n" +
	"apiVersion\x18\x01 \x01(\tR\n" +
	"apiVersion\x12$\n" +
	"\rschemaVersion\x18\x02 \x01(\tR\rschemaVersion\x120\n" +
	"\bmetadata\x18\x03 \x01(\v2\x14.proto.MetadataChartR\bmetadata\x12\"\n" +
	"\x05chart\x18\x04 \x01(\v2\f.proto.ChartR\x05chart\"\xca\x01\n" +
	"\fPutChartResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1e\n" +
	"\n" +
	"apiVersion\x18\x02 \x01(\tR\n" +
	"apiVersion\x12$\n" +
	"\rschemaVersion\x18\x03 \x01(\tR\rschemaVersion\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x06 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"maintainer\x18\a \x01(\tR\n" +
	"maintainer2\x9b\a\n" +
	"\x0fRegistryService\x123\n" +
	"\bPutChart\x12\x10.proto.StarChart\x1a\x13.proto.PutChartResp\"\x00\x12I\n" +
	"\x10GetChartMetadata\x12\x1e.proto.GetChartFromMetadataReq\x1a\x13.proto.GetChartResp\"\x00\x12J\n" +
	"\x0fGetChartsLabels\x12\x19.proto.GetChartsLabelsReq\x1a\x1a.proto.GetChartsLabelsResp\"\x00\x129\n" +
	"\n" +
	"GetChartId\x12\x14.proto.GetChartIdReq\x1a\x13.proto.GetChartResp\"\x00\x12>\n" +
	"\tGetCharts\x12\x13.proto.EmptyMessage\x1a\x1a.proto.GetChartsLabelsResp\"\x00\x12M\n" +
	"\x10GetMissingLayers\x12\x1a.proto.GetMissingLayersReq\x1a\x1b.proto.GetMissingLayersResp\"\x00\x12;\n" +
	"\vDeleteChart\x12\x15.proto.DeleteChartReq\x1a\x13.proto.EmptyMessage\"\x00\x126\n" +
	"\vUpdateChart\x12\x10.proto.StarChart\x1a\x13.proto.PutChartResp\"\x00\x12M\n" +
	"\x10SwitchCheckpoint\x12\x1a.proto.SwitchCheckpointReq\x1a\x1b.proto.SwitchCheckpointResp\"\x00\x125\n" +
	"\bTimeline\x12\x12.proto.TimelineReq\x1a\x13.proto.TimelineResp\"\x00\x121\n" +
	"\x06Extend\x12\x10.proto.ExtendReq\x1a\x13.proto.PutChartResp\"\x00\x128\n" +
	"\x06Search\x12\x10.proto.SearchReq\x1a\x1a.proto.GetChartsLabelsResp\"\x00\x128\n" +
	"\tPushLayer\x12\x13.proto.PushLayerReq\x1a\x14.proto.PushLayerResp\"\x00\x12P\n" +
	"\x11ListLayerVersions\x12\x1b.proto.ListLayerVersionsReq\x1a\x1c.proto.ListLayerVersionsResp\"\x00B\x1dZ\x1bgithub.com/c12s/starmap/apib\x06proto3"

var (
	file_starmap_proto_rawDescOnce sync.Once
	file_starmap_proto_rawDescData []byte
)

func file_starmap_proto_rawDescGZIP() []byte {
	file_starmap_proto_rawDescOnce.Do(func() {
		file_starmap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_starmap_proto_rawDesc), len(file_starmap_proto_rawDesc)))
	})
	return file_starmap_proto_rawDescData
}

var file_starmap_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_starmap_proto_goTypes = []any{
	(*PushLayerReq)(nil),            // 0: proto.PushLayerReq
	(*PushLayerResp)(nil),           // 1: proto.PushLayerResp
	(*ListLayerVersionsReq)(nil),    // 2: proto.ListLayerVersionsReq
	(*LayerVersionInfo)(nil),        // 3: proto.LayerVersionInfo
	(*ListLayerVersionsResp)(nil),   // 4: proto.ListLayerVersionsResp
	(*SearchReq)(nil),               // 5: proto.SearchReq
	(*ExtendReq)(nil),               // 6: proto.ExtendReq
	(*TimelineReq)(nil),             // 7: proto.TimelineReq
	(*TimelineResp)(nil),            // 8: proto.TimelineResp
	(*SwitchCheckpointResp)(nil),    // 9: proto.SwitchCheckpointResp
	(*SwitchCheckpointReq)(nil),     // 10: proto.SwitchCheckpointReq
	(*LayersResp)(nil),              // 11: proto.LayersResp
	(*GetMissingLayersReq)(nil),     // 12: proto.GetMissingLayersReq
	(*GetMissingLayersResp)(nil),    // 13: proto.GetMissingLayersResp
	(*GetChartIdReq)(nil),           // 14: proto.GetChartIdReq
	(*DeleteChartReq)(nil),          // 15: proto.DeleteChartReq
	(*GetChartsLabelsReq)(nil),      // 16: proto.GetChartsLabelsReq
	(*GetChartsLabelsResp)(nil),     // 17: proto.GetChartsLabelsResp
	(*GetChartFromMetadataReq)(nil), // 18: proto.GetChartFromMetadataReq
	(*GetChartResp)(nil),            // 19: proto.GetChartResp
	(*PutChartResp)(nil),            // 20: proto.PutChartResp
	nil,                             // 21: proto.SearchReq.TagsEntry
	nil,                             // 22: proto.SearchReq.ComponentTagsEntry
	nil,                             // 23: proto.LayersResp.DataSourcesEntry
	nil,                             // 24: proto.LayersResp.StoredProceduresEntry
	nil,                             // 25: proto.LayersResp.EventTriggersEntry
	nil,                             // 26: proto.LayersResp.EventsEntry
	nil,                             // 27: proto.LayersResp.EntrypointsEntry
	nil,                             // 28: proto.GetMissingLayersResp.DataSourcesEntry
	nil,                             // 29: proto.GetMissingLayersResp.StoredProceduresEntry
	nil,                             // 30: proto.GetMissingLayersResp.EventTriggersEntry
	nil,                             // 31: proto.GetMissingLayersResp.EventsEntry
	nil,                             // 32: proto.GetMissingLayersResp.EntrypointsEntry
	nil,                             // 33: proto.GetChartsLabelsReq.LabelsEntry
	(*StarChart)(nil),               // 34: proto.StarChart
	(*MetadataChart)(nil),           // 35: proto.MetadataChart
	(*Chart)(nil),                   // 36: proto.Chart
	(*DataSource)(nil),              // 37: proto.DataSource
	(*StoredProcedure)(nil),         // 38: proto.StoredProcedure
	(*EventTrigger)(nil),            // 39: proto.EventTrigger
	(*Event)(nil),                   // 40: proto.Event
	(*Entrypoint)(nil),              // 41: proto.Entrypoint
	(*EmptyMessage)(nil),            // 42: proto.EmptyMessage
}
var file_starmap_proto_depIdxs = []int32{
	3,  // 0: proto.ListLayerVersionsResp.versions:type_name -> proto.LayerVersionInfo
	21, // 1: proto.SearchReq.tags:type_name -> proto.SearchReq.TagsEntry
	22, // 2: proto.SearchReq.componentTags:type_name -> proto.SearchReq.ComponentTagsEntry
	34, // 3: proto.ExtendReq.chart:type_name -> proto.StarChart
	19, // 4: proto.TimelineResp.charts:type_name -> proto.GetChartResp
	11, // 5: proto.SwitchCheckpointResp.start:type_name -> proto.LayersResp
	11, // 6: proto.SwitchCheckpointResp.stop:type_name -> proto.LayersResp
	11, // 7: proto.SwitchCheckpointResp.download:type_name -> proto.LayersResp
	23, // 8: proto.LayersResp.dataSources:type_name -> proto.LayersResp.DataSourcesEntry
	24, // 9: proto.LayersResp.storedProcedures:type_name -> proto.LayersResp.StoredProceduresEntry
	25, // 10: proto.LayersResp.eventTriggers:type_name -> proto.LayersResp.EventTriggersEntry
	26, // 11: proto.LayersResp.events:type_name -> proto.LayersResp.EventsEntry
	27, // 12: proto.LayersResp.entrypoints:type_name -> proto.LayersResp.EntrypointsEntry
	28, // 13: proto.GetMissingLayersResp.dataSources:type_name -> proto.GetMissingLayersResp.DataSourcesEntry
	29, // 14: proto.GetMissingLayersResp.storedProcedures:type_name -> proto.GetMissingLayersResp.StoredProceduresEntry
	30, // 15: proto.GetMissingLayersResp.eventTriggers:type_name -> proto.GetMissingLayersResp.EventTriggersEntry
	31, // 16: proto.GetMissingLayersResp.events:type_name -> proto.GetMissingLayersResp.EventsEntry
	32, // 17: proto.GetMissingLayersResp.entrypoints:type_name -> proto.GetMissingLayersResp.EntrypointsEntry
	33, // 18: proto.GetChartsLabelsReq.labels:type_name -> proto.GetChartsLabelsReq.LabelsEntry
	19, // 19: proto.GetChartsLabelsResp.charts:type_name -> proto.GetChartResp
	35, // 20: proto.GetChartResp.metadata:type_name -> proto.MetadataChart
	36, // 21: proto.GetChartResp.chart:type_name -> proto.Chart
	37, // 22: proto.LayersResp.DataSourcesEntry.value:type_name -> proto.DataSource
	38, // 23: proto.LayersResp.StoredProceduresEntry.value:type_name -> proto.StoredProcedure
	39, // 24: proto.LayersResp.EventTriggersEntry.value:type_name -> proto.EventTrigger
	40, // 25: proto.LayersResp.EventsEntry.value:type_name -> proto.Event
	41, // 26: proto.LayersResp.EntrypointsEntry.value:type_name -> proto.Entrypoint
	37, // 27: proto.GetMissingLayersResp.DataSourcesEntry.value:type_name -> proto.DataSource
	38, // 28: proto.GetMissingLayersResp.StoredProceduresEntry.value:type_name -> proto.StoredProcedure
	39, // 29: proto.GetMissingLayersResp.EventTriggersEntry.value:type_name -> proto.EventTrigger
	40, // 30: proto.GetMissingLayersResp.EventsEntry.value:type_name -> proto.Event
	41, // 31: proto.GetMissingLayersResp.EntrypointsEntry.value:type_name -> proto.Entrypoint
	34, // 32: proto.RegistryService.PutChart:input_type -> proto.StarChart
	18, // 33: proto.RegistryService.GetChartMetadata:input_type -> proto.GetChartFromMetadataReq
	16, // 34: proto.RegistryService.GetChartsLabels:input_type -> proto.GetChartsLabelsReq
	14, // 35: proto.RegistryService.GetChartId:input_type -> proto.GetChartIdReq
	42, // 36: proto.RegistryService.GetCharts:input_type -> proto.EmptyMessage
	12, // 37: proto.RegistryService.GetMissingLayers:input_type -> proto.GetMissingLayersReq
	15, // 38: proto.RegistryService.DeleteChart:input_type -> proto.DeleteChartReq
	34, // 39: proto.RegistryService.UpdateChart:input_type -> proto.StarChart
	10, // 40: proto.RegistryService.SwitchCheckpoint:input_type -> proto.SwitchCheckpointReq
	7,  // 41: proto.RegistryService.Timeline:input_type -> proto.TimelineReq
	6,  // 42: proto.RegistryService.Extend:input_type -> proto.ExtendReq
	5,  // 43: proto.RegistryService.Search:input_type -> proto.SearchReq
	0,  // 44: proto.RegistryService.PushLayer:input_type -> proto.PushLayerReq
	2,  // 45: proto.RegistryService.ListLayerVersions:input_type -> proto.ListLayerVersionsReq
	20, // 46: proto.RegistryService.PutChart:output_type -> proto.PutChartResp
	19, // 47: proto.RegistryService.GetChartMetadata:output_type -> proto.GetChartResp
	17, // 48: proto.RegistryService.GetChartsLabels:output_type -> proto.GetChartsLabelsResp
	19, // 49: proto.RegistryService.GetChartId:output_type -> proto.GetChartResp
	17, // 50: proto.RegistryService.GetCharts:output_type -> proto.GetChartsLabelsResp
	13, // 51: proto.RegistryService.GetMissingLayers:output_type -> proto.GetMissingLayersResp
	42, // 52: proto.RegistryService.DeleteChart:output_type -> proto.EmptyMessage
	20, // 53: proto.RegistryService.UpdateChart:output_type -> proto.PutChartResp
	9,  // 54: proto.RegistryService.SwitchCheckpoint:output_type -> proto.SwitchCheckpointResp
	8,  // 55: proto.RegistryService.Timeline:output_type -> proto.TimelineResp
	20, // 56: proto.RegistryService.Extend:output_type -> proto.PutChartResp
	17, // 57: proto.RegistryService.Search:output_type -> proto.GetChartsLabelsResp
	1,  // 58: proto.RegistryService.PushLayer:output_type -> proto.PushLayerResp
	4,  // 59: proto.RegistryService.ListLayerVersions:output_type -> proto.ListLayerVersionsResp
	46, // [46:60] is the sub-list for method output_type
	32, // [32:46] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_starmap_proto_init() }
func file_starmap_proto_init() {
	if File_starmap_proto != nil {
		return
	}
	file_starmap_model_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_starmap_proto_rawDesc), len(file_starmap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_starmap_proto_goTypes,
		DependencyIndexes: file_starmap_proto_depIdxs,
		MessageInfos:      file_starmap_proto_msgTypes,
	}.Build()
	File_starmap_proto = out.File
	file_starmap_proto_goTypes = nil
	file_starmap_proto_depIdxs = nil
}
